### ISSUE TITLE
[Feature]: support Ollama backend

### ISSUE THREAD

**Issue by yankay** [k8sgpt-ai/k8sgpt#1064]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback, https://k8sgpt.slack.com/archives/C050SKW7SHF/p1712890993773069

### Is this feature request related to a problem?

None

### Solution Description

support Ollama like localai. 

### Benefits

The Ollama can make it easier for users to interact with K8SGPT.

**Comment by wilmardo** [comment]
On my Mac I did this to make it work. Installed ollama as application, then:
```
k8sgpt auth add --backend localai --model llama2 --baseurl http://localhost:11434/v1
k8sgpt auth default -p localai. # sets it as default, not really needed
```

**Comment by arbreezy** [comment]
yes we can use localai, cause both support the OpenAI's API spec, but I guess we can surface it as its own backend since it's a different project that localai

**Comment by JuHyung-Son** [comment]
if they have same inference interface, how about using opensource bankend which can `ollama`, `localai` can use.

**Comment by ronaldpetty** [comment]
Hello, any comment on this code to support Ollama directly?

https://github.com/k8sgpt-ai/k8sgpt/pull/1131

Seems to be working locally for me.

```
# run ollama, assuming locally, here with llama3
make build
./bin/k8sgpt auth add --backend ollama --model llama3 --baseurl http://localhost:11434/v1
kubectl run brokenpod --image=breakit:v1.2.3 
./bin/k8sgpt analyze --explain --backend ollama # output looks good
```

**Comment by yankay** [comment]
> Hello, any comment on this code to support Ollama directly?
> 
> #1131
> 
> Seems to be working locally for me.
> 
> ```
> # run ollama, assuming locally, here with llama3
> make build
> ./bin/k8sgpt auth add --backend ollama --model llama3 --baseurl http://localhost:11434/v1
> kubectl run brokenpod --image=breakit:v1.2.3 
> ./bin/k8sgpt analyze --explain --backend ollama # output looks good
> ```

HI @ronaldpetty , follow the https://github.com/k8sgpt-ai/k8sgpt/pull/1065#issuecomment-2073383889.
Using the official go client makes more sense than the OpenAI client. :-)
