### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by AjinkyaBapat** [k8sgpt-ai/k8sgpt#110]
When I run `brew install k8sgpt`, it gives me following error:
`==> Installing k8sgpt from k8sgpt-ai/k8sgpt
Error: The following formula cannot be installed from bottle and must be
built from source.
  k8sgpt
Install Clang or run brew install gcc.`

I did run `brew install gcc` but it's still the same.

**Comment by AlexsJones** [comment]
Hey thanks for the issue, can you let us know the following? ->
- HostOS
- Architecture ( amd64/arm64 etc )

**Comment by thschue** [comment]
Found this issue here: https://medium.com/@edwardbaeg9/using-homebrew-on-windows-10-with-windows-subsystem-for-linux-wsl-c7f1792f88b3

If you are running in WSL, please try the following: ```
sudo apt-get update
sudo apt-get install build-essential 
```

**Comment by iamunnip** [comment]
The issue is solved for me after following the above commands.
Thank you.
