### ISSUE TITLE
[bug]: failed while calling AI provider openai

### ISSUE THREAD

**Issue by njnuwjq** [k8sgpt-ai/k8sgpt#1111]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

k8sgpt: 0.3.30 (Homebrew), built at: 2024-04-26T09:17:15Z

### Kubernetes Version

Server Version: v1.28.5

### Host OS and its Version

mac

### Steps to reproduce

1.  ~ % k8sgpt generate

Opening: https://beta.openai.com/account/api-keys to generate a key for openai

Please copy the generated key and run `k8sgpt auth add` to add it to your config file

2.  ~ % k8sgpt auth 
Warning: backend input is empty, will use the default value: openai
Warning: model input is empty, will use the default value: gpt-3.5-turbo
Enter openai Key: openai added to the AI backend provider list

3.  ~ % k8sgpt  analyse                                                         
AI Provider: AI not used; --explain not set

0: Service default/release-name-hana-operator-controller-manager-metrics-service()
- Error: Service has no endpoints, expected label app.kubernetes.io/instance=release-name
- Error: Service has no endpoints, expected label app.kubernetes.io/name=hana-operator
- Error: Service has no endpoints, expected label control-plane=controller-manager

4.  ~ % k8sgpt  analyse --explain
   0% |                                                                                                                                                                            | (0/3, 0 it/hr) [0s:0s]
Error: failed while calling AI provider openai: error, status code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.

### Expected behaviour

4.  ~ % k8sgpt  analyse --explain

could ananlyse the result with openai

**Comment by JuHyung-Son** [comment]
Are you sure you've got the settings right? I don't see any issues with k8sgpt.

**Comment by njnuwjq** [comment]
thanks for your reply


got the security key from openapi here
-------------------------------
NAME	<<SECRET KEY>>	CREATED	LAST USED 	CREATED BY	PERMISSIONS


and pasted it @ step 2
  ~ % k8sgpt auth
  Warning: backend input is empty, will use the default value: openai
  Warning: model input is empty, will use the default value: gpt-3.5-turbo
  Enter openai Key:      <<< pasted the security key here
  
  not any error occurs, just report that openai added to the AI backend provider list
  
  checked the configuration file but there's nothing 
   --config string        Default config file (/Users/xxxxxx/Library/Application Support/k8sgpt/k8sgpt.yaml)
    ls /Users/xxxxxx/Library/Application Support/k8sgpt/k8sgpt.yaml 
    ls: /Users/xxxxxx/Library/Application: No such file or directory
  
   ~ % k8sgpt  auth list
Default: 
> openai
Active: 
> openai
Unused: 
  
 also tried with configuration file
  ~ % cat k8sgpt.yaml
  openai:
    api_key: sk-k8s-olTikkFN5cfolIz2ym6xxxxxx
  
  ~ %  k8sgpt analyse --explain --config  ./k8sgpt.yaml 
    Error: AI provider not specified in configuration. Please run k8sgpt auth

**Comment by njnuwjq** [comment]
here miss a \ after /Users/xxxxx/Library/Application

--config string Default config file (/Users/xxxxxx/Library/Application Support/k8sgpt/k8sgpt.yaml)

 % cat  /Users/xxxxx/Library/Application\ Support/k8sgpt/k8sgpt.yaml
ai:
    providers:
        - name: openai
          model: gpt-3.5-turbo
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
        - name: openai
          model: gpt-3.5-turbo
          password: sk-proj-zBPbDQdWE7ai9iaGR1iWT3BlbkFJLQ2KJKyQrWtXOu6ZpMg6
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
          
the first provider don't provide    password and it's always try with the first one
thus it failed all the time

so it's solved
