### ISSUE TITLE
[Bug]: Windows executable not working properly

### ISSUE THREAD

**Issue by MR-Os1** [k8sgpt-ai/k8sgpt#1118]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.31

### Host OS and its Version

Windows 11

### Steps to reproduce

1. Download windows x64_86 binary.
2. add to path

### Expected behaviour

get help command or something

### Actual behaviour

panic: unable to redefine 'c' shorthand in "add" flagset: it's already used for "topp" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000d04700, 0xc00096b4a0)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x3e7
github.com/spf13/pflag.(*FlagSet).VarPF(0x28?, {0x3364b70, 0x4dc5cc0}, {0x2c08dbd, 0x4}, {0x3331b20, 0x1}, {0x2d0a7cd, 0xca})
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x14f
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).Int32VarP(0x2ce6ad6?, 0x5e?, {0x2c08dbd?, 0x10?}, {0x3331b20?, 0x4d65680?}, 0x3331b18?, {0x2d0a7cd?, 0x0?})
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/int32.go:50 +0x45
github.com/k8sgpt-ai/k8sgpt/cmd/auth.init.0()
        /home/runner/work/k8sgpt/k8sgpt/cmd/auth/add.go:166 +0x229

**Comment by YuviGold** [comment]
The latest version (v0.3.31) panics on mac and linux as well.

```
panic: unable to redefine 'c' shorthand in "add" flagset: it's already used for "topp" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x140009ecb00, 0x140008fa000)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x364
github.com/spf13/pflag.(*FlagSet).VarPF(0x1?, {0x1051384b0, 0x106ada2b0}, {0x1040c188c, 0x4}, {0x1047de090, 0x1}, {0x1041c08ca, 0xca})
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x148
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).Int32VarP(0x106a6fb60?, 0x104ccfa40?, {0x1040c188c?, 0x10222e544?}, {0x1047de090?, 0x10222e544?}, 0x0?, {0x1041c08ca?, 0x10419cc2c?})
        /home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/int32.go:50 +0x50
github.com/k8sgpt-ai/k8sgpt/cmd/auth.init.0()
        /home/runner/work/k8sgpt/k8sgpt/cmd/auth/add.go:166 +0x1f4
```

**Comment by AlexsJones** [comment]
Fix in flight!
