### ISSUE TITLE
Filter by namespace

### ISSUE THREAD

**Issue by wiardvanrij** [k8sgpt-ai/k8sgpt#112]
I would like to run the analyze for a specific namespace instead of the entire cluster. --filter by namespace or just a --namespace flag would be ideal.

**Comment by AlexsJones** [comment]
Great idea, we'll put this into an upcoming release

**Comment by yurymkomarov** [comment]
I think we need not only namespace, but exact target. like:
```
$: k8sgpt analyze --namespace $NAMESPACE --%resource_type% $RESOURCE_NAME
```
in case if you want to analyze pod/service/deployment/statefulset and etc.

**Comment by thschue** [comment]
@yurymkomarov: Thank you for your suggestion. We already have the ability to filter for resource types (`--filter`). I'm curious if we should add naming patterns in there.

@AlexsJones: What do you think about this?

**Comment by AlexsJones** [comment]
I think filtering namespace is an easy thing to implement and we will do it. Exact resource names could be doable.. GVR ( group version resource) but it has a maintenance over head so I am a bit reluctant unless there is an issue it solves
