### ISSUE TITLE
Pass Headers while authenticating to AI backends

### ISSUE THREAD

**Issue by atul86244** [k8sgpt-ai/k8sgpt#1121]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Need a way to pass headers for authenticating to AI backends.

### Solution Description

I am trying to point to an AI backend which needs few headers to be passed along with API key for authentication. How can I do this from k8sGPT?

### Benefits

This will help use custom AI backends.

### Potential Drawbacks

NA

### Additional Information

NA

**Comment by JuHyung-Son** [comment]
we need to implement it
