### ISSUE TITLE
docs: update "CLI Installation" section in README.md

### ISSUE THREAD

**Issue by ut-wangbo** [k8sgpt-ai/k8sgpt#1126]
1. user can pass the rpm url to the rpm command.  (^_^)
e.g.  rpm -ivh  https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.3.32/k8sgpt_386.rpm
(Unfortunately, dpkg and apk do not support using url)

2. there is a duplicate "-i" option in the 64 bit rpm installation command.  (-_-!)
![i](https://github.com/k8sgpt-ai/k8sgpt/assets/86947360/95466572-c32d-42b1-a076-06f53805e9ae)

3. user need to add the "--allow-untrusted" option since our apk package is not signed. Otherwise, the installation will fail.

4. Alpine Linux does not have "curl" command by default, but has "wget" .

5. there is an extra and meaningless "x" at the end of the "APK-based installation (Alpine)" section. (-_-!)
![x](https://github.com/k8sgpt-ai/k8sgpt/assets/86947360/a9f4a19c-6229-479a-8f42-0381a3c986a5)

**Comment by AlexsJones** [comment]
Thanks for spotting this
