### ISSUE TITLE
add openai organizationID config

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt#1130]
openai requires organizationID in request for some users.
and it looks like projectID is not mandatory see https://github.com/sashabaranov/go-openai/issues/757 

so only organizationID in `OpenAI` and `AzureOpenAI` need to be added.

**Comment by VaibhavMalik4187** [comment]
@JuHyung-Son the idea is to add the `organizationID` as an optional parameter in the backend config right? And this should only be allowed for the `OpenAI` and `AzureOpenAI` backends?

**Comment by JuHyung-Son** [comment]
yes

**Comment by VaibhavMalik4187** [comment]
> yes. you can check the pr

Okay. I thought this issue was up for grabs. Thanks for letting me know.
