### ISSUE TITLE
Allow for support for Azure OpenAI Services

### ISSUE THREAD

**Issue by msandbu** [k8sgpt-ai/k8sgpt#117]
Since many (including myself) with organizations will be using ChatGPT as part of Azure OpenAI Service. The feature should also allow the ability to point to ChatGPT running on Azure OpenAI Services. 

It is using the same API but different endpoint https://openaichatgpt.openai.azure.com, could for instance be a featureflag to point it to another endpoint?

**Comment by AlexsJones** [comment]
We have the ability to switch the `--backend` and an `IAI` interface which should make implementing it pretty easily. 
Do you know if there is a golang based SDK? The current SDK we use is tightly coupled to OpenAI public endpoints though I could look at whether we can modify that.

**Comment by msandbu** [comment]
Are you using this? https://github.com/sashabaranov/go-openai (Do not believe there is
Perhaps it would be better if I get support for the Azure OpenAI endpoint there first make it easier to add the new backend here?

**Comment by roberthstrand** [comment]
I'm looking into this going forward. The SDK we are using has an open issue on support for Azure OpenAI, but I will look into several solutions for this.

**Comment by AlexsJones** [comment]
I feel we might want to build our own SDK to control our destiny a bit more.

**Comment by roberthstrand** [comment]
I was thinking of that as well. Let's have a discussion about it tomorrow, when I got more time :)

**Comment by stulzq** [comment]
This is a solution：https://github.com/stulzq/azure-openai-proxy

**Comment by jnytnai0613** [comment]
> Are you using this? https://github.com/sashabaranov/go-openai (Do not believe there is Perhaps it would be better if I get support for the Azure OpenAI endpoint there first make it easier to add the new backend here?

Hi!
It seems that [sashabaranov/go-openai](https://github.com/sashabaranov/go-openai/pull/214) already supports Azure OpenAI.
https://github.com/sashabaranov/go-openai/releases/tag/v1.6.0

**Comment by arbreezy** [comment]
I have created a draft PR to introduce azure open ai provider, bear with us a little longer as it also includes other changes that need to test first before merging it

**Comment by arbreezy** [comment]
@msandbu , would you be able to beta-test the feature since I don't have an azure openai deployment up and running?
