### ISSUE TITLE
[Question]: Get following error while calling k8sgpt analyze -e : Error: failed while calling AI provider openai: error, status code: 503 

### ISSUE THREAD

**Issue by bizhao** [k8sgpt-ai/k8sgpt#1232]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.40

### Kubernetes Version

v1.28.11

### Host OS and its Version

MacOS 14.5

### Steps to reproduce

1. Run k8sgpt auth to add OpenAI as backend with OpenAI Key.
2. run  k8sgpt analyze -e  and get:
   0% |                                                                                                                                                                                    | (0/1, 0 it/hr) [0s:0s]
Error: failed while calling AI provider openai: error, status code: 503, message: invalid character '<' looking for beginning of value

### Expected behaviour

Seems it fails to call OpenAI backend. 
Anywhere I can check to see why it fails?
And the error message should be more meaningful.

**Comment by matthisholleville** [comment]
Hi! The 503 status code indicates that OpenAI is currently unavailable. Are you experiencing this issue consistently or only intermittently?

**Comment by bizhao** [comment]
I get this output consistently.
But it looks related to my internet connection.  Is there any log I can check the detailed request/response data?
