### ISSUE TITLE
Typo in the k8s api-resource

### ISSUE THREAD

**Issue by daasol** [k8sgpt-ai/k8sgpt#1240]
https://github.com/k8sgpt-ai/k8sgpt/blob/477ef155d32f4d81ca3bee612644f51fc1098cdc/pkg/analyzer/validating_webhook.go#L31

Hi, I found a typo while using k8sgpt. It seems like you intended to use `ValidatingWebhookConfiguration`, but it appears as `ValidatingWebhookConfgiguration`  in the result. It looks like it needs to be fixed.

**Comment by arbreezy** [comment]
nice catch @daasol :pray:
