### ISSUE TITLE
[Question]: K8sgpt CRD cannot set resource limit memory

### ISSUE THREAD

**Issue by dung2k1deptrai** [k8sgpt-ai/k8sgpt#1277]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

When I create K8sgpt resource CRD in openshift OKD, pod always crash with OOM killed

### Expected behaviour

I set resource request to increase memory in Deployment but it always set as default like this:
        - resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 156Mi
I see that deployment managed by CRD but i couldn't see any field to declare resource limit in that.

**Comment by AlexsJones** [comment]
To clarify - the ask here is to enable the K8sGPT CR to control the resource constraints of the deployment? This seems pretty sensible.

**Comment by dung2k1deptrai1** [comment]
> To clarify - the ask here is to enable the K8sGPT CR to control the resource constraints of the deployment? This seems pretty sensible.

This is exactly I wanted right now

**Comment by vivekk16** [comment]
Hi @AlexsJones

I'm interested in contributing to this issue. Could you provide guidance on how to get started?
