### ISSUE TITLE
docs: Add link to the new slack channel. 

### ISSUE THREAD

**Issue by sudiptob2** [k8sgpt-ai/k8sgpt#134]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

## Describe the solution you'd like

At present, the link to the slack channel mentioned in the [Readme.md](https://github.com/k8sgpt-ai/k8sgpt#community) is redirects to the old slack channel. However, a new [slack workspace](https://k8sgpt.slack.com) for K8GPT has created Ref: [https://k8sgpt.slack.com](https://k8sgpt.slack.com/). We need to update the readme and refer to the new link.

## Potential drawbacks

Should we keep the old link also, so that new users can refer to the old discussions?

**Comment by jayaramcloud** [comment]
How do I get invited to https://k8sgpt.slack.com?
