### ISSUE TITLE
feature: Create analyzer for ingress resources

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/k8sgpt#136]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
I think it would be useful, if we'd be able to analyze ingress resources to find out if everything is configured correctly and obviously if it should be working technically.

In the first step, we could try to find out if services referred to in the ingress object are existing, and maybe if they are responsive.

## Benefits for the project and its users
Users could detect and troubleshoot ingress issues

**Comment by matthisholleville** [comment]
Great idea 👍 
We could consider checking in a second step that the secret used for the certificate actually exists. 

What do you think?
