### ISSUE TITLE
feature: Selective Analyzer Execution through Upstream Filtering for Optimized Analysis

### ISSUE THREAD

**Issue by matthisholleville** [k8sgpt-ai/k8sgpt#146]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

## Describe the solution you'd like

I noticed that when a filter is added during analysis, all analyzers are executed, which makes the analysis very long even if we only want to retrieve the services.

The filter is applied during the merging of errors to display only what the user has indicated in the filter argument. Shouldn't the filter be applied upstream so that only the analyzer we are interested in is executed?

## Benefits for the project and its users

Improvement of Performance in Adding Filters

**Comment by AlexsJones** [comment]
Yes, this is a great suggestion and as you say would speed things up a lot.. I can change this in a moment

**Comment by AlexsJones** [comment]
Completed in https://github.com/k8sgpt-ai/k8sgpt/pull/149

**Comment by matthisholleville** [comment]
Good job @AlexsJones !
