### ISSUE TITLE
bug: Cached response when switching kubectl context

### ISSUE THREAD

**Issue by alegri90** [k8sgpt-ai/k8sgpt#150]
Checklist:

* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've included steps to reproduce the bug.
* [X] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

After changing kubectl context to another cluster, it seems as if k8sgpt just respons with a cache without actually checking. I get the same (identical) response eventhough kubeconfig context was changed.

### Your environment

* Version of Kubernetes
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.6
* Host OS and its version / If windows, is it WSL?
System Version: macOS 13.1 (22C65)
Kernel Version: Darwin 22.2.0
* Version of k8sgpt
k8sgpt version 0.1.2

### Steps to reproduce

* Step 1
Execute an `analyze` 
* Step 2
Switch kubectl context to a different cluster
* Step 3
Execute another `analyze`

### Expected behaviour
I expected to get a new analyze result from the new cluster context.

### Actual behaviour

I got the identical response as from when I first ran the `analyze`

### Additional context / screenshots

I've also tried deleting `~/.k8sgpt.yaml` as well as `~/.kube/config` and thereafter reset a totally fresh kubeconfig context and reinitated the `k8sgpt auth`. The respons I got after a `k8sgpt analyze` was the exact same as before, from the cluster I no longer have in my context.

The progress loading is at `0%` and the time usage output says `| (0/4, 0 it/hr) [0s:0s]0`

Additionally, also tried from a different terminal session. Also tried switching to Terminal.app instead of iTerm. Also switched from omzsh to bash. I get the cached response immediately...

I verified that kubectl had correctly switch context between each step and in all the different shell sessions, and that. `k8sgpt` had not switched. It still gave the identical response.

**Comment by AlexsJones** [comment]
Fixed in https://github.com/k8sgpt-ai/k8sgpt/pull/155

**Comment by alegri90** [comment]
@AlexsJones - Thanks for the quick response, but alas - v.0.1.4 gives the same incorrect result. 

I did a the following, if it is of any help...;
```sh
➜  ~ brew upgrade k8sgpt
==> Upgrading k8sgpt-ai/k8sgpt/k8sgpt
  0.1.2 -> 0.1.4

➜  ~ k8sgpt version
k8sgpt version 0.1.4

➜  ~ kubectl config use-context <CLUSTER_1>
Switched to context <CLUSTER_1>

➜  ~ k8sgpt analyse
   0% |                                                                                                                                                                                  | (0/4, 0 it/hr) [0s:0s]0 kube-system/kube-prometheus-stack-kube-controller-manager(kube-prometheus-stack-kube-controller-manager)
- Error: Service has no endpoints, expected label component=kube-controller-manager
1 kube-system/kube-prometheus-stack-kube-etcd(kube-prometheus-stack-kube-etcd)
- Error: Service has no endpoints, expected label component=etcd
2 kube-system/kube-prometheus-stack-kube-proxy(kube-prometheus-stack-kube-proxy)
- Error: Service has no endpoints, expected label k8s-app=kube-proxy
3 kube-system/kube-prometheus-stack-kube-scheduler(kube-prometheus-stack-kube-scheduler)
- Error: Service has no endpoints, expected label component=kube-scheduler


➜  ~ kubectl config use-context <CLUSTER_2>
Switched to context <CLUSTER_2>

# verifying that kubectl has switched by inspecting that it is in fact a different cluster
➜  ~ kubectl get ns


➜  ~ k8sgpt analyse
   0% |                                                                                                                                                                                  | (0/4, 0 it/hr) [0s:0s]0 kube-system/kube-prometheus-stack-kube-controller-manager(kube-prometheus-stack-kube-controller-manager)
- Error: Service has no endpoints, expected label component=kube-controller-manager
1 kube-system/kube-prometheus-stack-kube-etcd(kube-prometheus-stack-kube-etcd)
- Error: Service has no endpoints, expected label component=etcd
2 kube-system/kube-prometheus-stack-kube-proxy(kube-prometheus-stack-kube-proxy)
- Error: Service has no endpoints, expected label k8s-app=kube-proxy
3 kube-system/kube-prometheus-stack-kube-scheduler(kube-prometheus-stack-kube-scheduler)
- Error: Service has no endpoints, expected label component=kube-scheduler


# 👆 these services does not exist in CLUSTER_2, and the response / result came instantly (seems cached 🤷‍♂️)
```
