### ISSUE TITLE
feature: analyzer for network policies

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/k8sgpt#157]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [x] Yes
* [ ] No

if you set deny-all nw-policies for your namespaces per default and you need to define each allow-policy it could be really frustrating when your frontend service cannot connect to the backend service. you need to check

- is the policy correct (labels, indents, ports, ..)
- is the backend service responsive
- run some curl/wget command in the frontend service, which you probably don't have, attach debug containers, ...

## Describe the solution you'd like
in the first place we could check if the "from" and "to" selectors in network policies match existing objects, probably also checking targetPorts

## Benefits for the project and its users
analyzing network policy issues gets simpler

**Comment by matthisholleville** [comment]
Good idea to add network policies analyzer 👍 

But I'm not sure as a user I would like k8sgpt to execute anything on my cluster. It remains to be seen what the community thinks, but I like the idea that k8sgpt only performs read analysis on objects.

**Comment by arbreezy** [comment]
the read only checks have been implemented in this [PR](https://github.com/k8sgpt-ai/k8sgpt/pull/267/files), shall we close the ticket?

**Comment by thschue** [comment]
Should be solved with #267
