### ISSUE TITLE
feature: default filters vs opt-in

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#158]
Checklist:
* [x ] I've searched for similar issues and couldn't find anything matching
* [x ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [ x] No

As we start to build out more capabilities, there are those that are not necessarily catching "errors" but more best-practice or good guidance on how to operate with Kubernetes. One such example os PDB ( Pod disruption budget ), it is not an error not to have this on a deployment/sts/ds but it is good practice for when you wish to roll a small deployment without loss of availability.

I propose that we have a mechanism to list/set default filters

e.g.
```
k8sgpt filters list
> Pod
> Service
> Ingress
etc..
```
Then you could add or remove a filter
```
k8sgpt filters add: <Resource> 
// Check if its found
```

```
k8sgpt filters remove: <Resource>
// Check if its found
```

This would then form the basis of a new array we would pull from viper and loop over 
e.g. 

```
func RunAnalysis(ctx context.Context, filters []string, config *AnalysisConfiguration,
	client *kubernetes.Client,
	aiClient ai.IAI, analysisResults *[]Analysis) error {

      // HERE WE WOULD BUILD THE ANALYZER MAP BASED OFF OF viper.Get("default_filters")


	// if there are no filters selected then run all of them
	if len(filters) == 0 {  
		for _, analyzer := range analyzerMap { 
			if err := analyzer(ctx, config, client, aiClient, analysisResults); err != nil {
				return err
			}
		}
		return nil
	}

	for _, filter := range filters {
		if analyzer, ok := analyzerMap[filter]; ok {
			if err := analyzer(ctx, config, client, aiClient, analysisResults); err != nil {
				return err
			}
		}
	}
	return nil
}
```

**Comment by matthisholleville** [comment]
As we discussed together, I'm fine with it. I'm interested in proposing an implementation for this issue.

**Comment by thschue** [comment]
@matthisholleville: Assigned this issue to you
