### ISSUE TITLE
feature: analyzer for Pod Disruption Budget

### ISSUE THREAD

**Issue by matthisholleville** [k8sgpt-ai/k8sgpt#163]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

## Describe the solution you'd like

It could be highly beneficial to conduct an analysis of pdb resources to ensure that everything is configured correctly and functioning as expected.

My initial idea is to perform a simple check to ensure that the pdb is applicable to at least one existing resource.

## Benefits for the project and its users

Users could detect and troubleshoot pdb issues

## Additional context

As discussed with @AlexsJones , this analyzer may not be enabled by default, but only if the user specifies it by running `k8sgpt filters add pdb`. This issue depend #161

**Comment by yeahservice** [comment]
As posted in slack, I would like to give this a shot.
