### ISSUE TITLE
bug: `kubecontext` flag has no effect

### ISSUE THREAD

**Issue by Antvirf** [k8sgpt-ai/k8sgpt#164]
Checklist:

* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've included steps to reproduce the bug.
* [x] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

Relevant to issue https://github.com/k8sgpt-ai/k8sgpt/issues/114 that was closed in PR https://github.com/k8sgpt-ai/k8sgpt/pull/155.

**Primary issue:** The `kubecontext` flag has no effect. Current context is always used despite any given input.

**Secondary issue:** The functionality isn't described in the docs - happy to submit chore PRs to document how this works if this is an issue from my end.

### Your environment

* Version of Kubernetes
  ```
  Client Version: v1.26.1
  Kustomize Version: v4.5.7
  Server Version: v1.24.10-eks-48e63af
  ```
* Host OS and its version / If windows, is it WSL?
  ```
  MacOS Ventura 13.2.1
  ```
* Version of k8sgpt
  [v0.1.4](https://github.com/k8sgpt-ai/k8sgpt/releases/tag/v0.1.4)

### Steps to reproduce

Assumes you have a `kubeconfig` with a functional current context - e.g. you can run `kubectl get nodes` successfully.

1. Download k8sgpt v0.1.4
2. Run `./k8sgpt auth`, put some random key as we wont use it anyway
3. Run `./k8sgpt analyze` - works fine, uses your default context
4. Run `./k8sgpt analyze --kubecontext aContextThatDoesNotExist` - **runs without issue, as it uses your default context despite any given value**

### Expected behaviour

If I provide a context that exists, that context should be used for the analysis.

If I provide a context that does not exist, the tool should crash or fail (hopefully with a nice error message explaining why.)

### Actual behaviour

Current context of your `kubeconfig` is always used. Providing a context that doesn't exist will still use the default, leading to misleading behaviour as shown below.

```
# without context flag - uses current context, this cluster is healthy
❯ ~/Desktop/k8sgpt_Darwin_arm64_0.1.4/k8sgpt analyze
{ "status": "OK" }

# with context flag - current context is used anyway
❯ ~/Desktop/k8sgpt_Darwin_arm64_0.1.4/k8sgpt analyze --kubecontext aContextThatDoesNotExist
{ "status": "OK" } # this is a lie - the given context doesn't even exist
```

**Comment by matthisholleville** [comment]
Hello,

Indeed, I believe that we never utilize this section of the code : https://github.com/k8sgpt-ai/k8sgpt/blob/main/cmd/root.go#L65
