### ISSUE TITLE
feature: add --auth-string flag to auth

### ISSUE THREAD

**Issue by shivamdurgbuns** [k8sgpt-ai/k8sgpt#180]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

Upon usage I have seen that in order to provide the API key using auth command we have to pass input to the prompted line

## Describe the solution you'd like

I am suggesting to have an extra flag names --auth-string, that could be used to provide API to auth command into the same line.

## Benefits for the project and its users

This will benefit in places such as CI/CD or any scripts where we have to single the key in the same single line command rather than waiting for input, we can directly pass the secret in the same line.

**Comment by shivamdurgbuns** [comment]
I would be working on this one, so please assign it to me. Thank you :)

**Comment by AlexsJones** [comment]
I think this could be useful, thanks I will add it to the issue backlog

**Comment by AlexsJones** [comment]
I would recommend we use something more standard like `--password-from-stdin` or `--password`

**Comment by matthisholleville** [comment]
@shivamdurgbuns I am working on an integration with GitLab CI, so I also needed this functionality. I have submitted a merge request. I hope you haven't started anything on your end? 😞

**Comment by shivamdurgbuns** [comment]
> @shivamdurgbuns I am working on an integration with GitLab CI, so I also needed this functionality. I have submitted a merge request. I hope you haven't started anything on your end? 😞 

Oh! I had started working on, but your pr looks ok. You should have waited a little I was about to test and push those changes.

**Comment by matthisholleville** [comment]
Sorry. I'll contact you upstream next time.
