### ISSUE TITLE
feature: nix packages

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#181]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

Provide at least one format of Linux native packaging

**Comment by thschue** [comment]
Added creation of apk, deb and rpm packages and they are published with releases.
