### ISSUE TITLE
feature: support gpt4all 

### ISSUE THREAD

**Issue by shulzip** [k8sgpt-ai/k8sgpt#185]
having gpt4all supported instead of openai will enable us to run k8sgpt locally
here is the repo: https://github.com/nomic-ai/gpt4all/tree/main

**Comment by AlexsJones** [comment]
Hey, there is a long term project objective to do this,.

Please follow this issue for tracking -> https://github.com/k8sgpt-ai/k8sgpt/issues/188

Thank you!
