### ISSUE TITLE
feature: alias "filter" to filters

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#187]
Checklist:
* [x ] I've searched for similar issues and couldn't find anything matching
* [x ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [x ] Yes
* [ ] No

## Describe the solution you'd like

```
❯ go run main.go filter list
Error: unknown command "filter" for "k8sgpt"

Did you mean this?
	filters

Run 'k8sgpt --help' for usage.
exit status 1
```

`filter` should alias for `filters` as a convenience

**Comment by rakshitgondwal** [comment]
Hey @AlexsJones! I would like to fix this.
