### ISSUE TITLE
Local  model support

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#188]
- LLaMa
- GPT4ALL

**Comment by mudler** [comment]
hey @AlexsJones :wave: I might help here, I've been working on the [llama.cpp](https://github.com/ggerganov/llama.cpp) binding for go, that allows model to be loaded directly from consumer grade hardware. you can find that over here: https://github.com/go-skynet/go-llama.cpp, hopefully that can help! 

I'm also working on making an API out of it that mimics openAI, so can be used as a drop-in replacement, you can find that here: https://github.com/go-skynet/llama-cli

**Comment by AlexsJones** [comment]
Hey @mudler thanks for dropping by, this is precisely one of the backends I would love to adopt.
I would be very keen to collaborate where possible on this. 

I can see usecases where a company may wish to use llama + k8sgpt in a private cloud.. exciting stuff if we work together. 
WDYT?

**Comment by mudler** [comment]
@AlexsJones definitely interested here, consider me hooked!

I see as well a lot of potential, especially if we think about situations more privacy-focused, and where vendor lock-in it's not an option. 

I'm happy to jump in and contribute!

**Comment by mudler** [comment]
I've made some progress into mimicking the OpenAI api, supporting multiple local models, so I think I'm pretty close. 

What I miss is a way to tell k8sgpt to use another API host, It seems to me that's not possible yet, or am I missing something?

**Comment by AlexsJones** [comment]
> I've made some progress into mimicking the OpenAI api, supporting multiple local models, so I think I'm pretty close.
> 
> What I miss is a way to tell k8sgpt to use another API host, It seems to me that's not possible yet, or am I missing something?

It's actually possible but we'd have to write a provider..

Do you want me to put something together if you can give me the local endpoint details?

**Comment by AlexsJones** [comment]
We would need to "for now" write an in-tree provider against this API

**Comment by mudler** [comment]
> > I've made some progress into mimicking the OpenAI api, supporting multiple local models, so I think I'm pretty close.
> > What I miss is a way to tell k8sgpt to use another API host, It seems to me that's not possible yet, or am I missing something?
> 
> It's actually possible but we'd have to write a provider..
> 
> Do you want me to put something together if you can give me the local endpoint details?

that would definitely speed up things, I have few changes still to accommodate for having a good 1:1 "clone" of the OpenAI API and tag a release, but that also means that less changes should be required here (I think we can just use the same OpenAI client, but with a different host?). After that I was planning to have a look at the changes that might be required here so can have a good testbench for local iteration.

Another point that I almost forgot - we need also a configuration to specify the model to use as well in the several API calls, any input is appreciated!

**Comment by mudler** [comment]
> Hey @mudler, I can try to help you with k8sgpt changes if you want to collaborate on this.
> Feel free to touch base!

@arbreezy I'd be more than happy! I think I've almost got all the pieces from my side for a first try. I'll keep you posted when I've an API container image ready and docs with it. I'm about to tag now a release (  https://github.com/go-skynet/llama-cli/releases/tag/v0.6) which is working already - but docs aren't aligned.

There is another point to worth mentioning as part of this story - free models available up to now have a restricted license, as such some extra steps are needed, but nothing blocking I believe.

**Comment by mudler** [comment]
:wave: I've just tagged a new version that supports the OpenAI API, documentation on the supported calls is here: https://github.com/go-skynet/llama-cli#supported-openai-api-endpoints

Next I'll try to have a look at k8sgpt closer as soon as I have another cycle to dedicate to it so can likely help you there and try this out too! 

This sounds very exciting and promising, we could even have dedicated, fine-tuned model just for suggesting Kubernetes solutions, making it quite faster instead of using generic models.

**Comment by mudler** [comment]
Added docker-compose file with easier-to-follow instructions https://github.com/go-skynet/llama-cli#usage sorry didn't had time to deep dive yet on k8sgpt, kubecon week, but it's next thing on my list :)

**Comment by mudler** [comment]
@arbreezy if you want to play with it meanwhile, feel free!

**Comment by mudler** [comment]
done some progress here! see the PR =)

**Comment by arbreezy** [comment]
amazing, I was about to pick this up during the weekend.
thanks for all the effort @mudler.
