### ISSUE TITLE
docs: create documentation for installation via rpm, deb, apk

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/k8sgpt#202]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
With version [0.1.8](https://github.com/k8sgpt-ai/k8sgpt/releases/tag/v0.1.8), we started building packages for various distributions. Therefore, the installation process should get documented.

**Comment by rakshitgondwal** [comment]
I would like to work on this!

**Comment by thschue** [comment]
Assigned this to you. I think this should be done in the [docs](https://github.com/k8sgpt-ai/docs), therefore I'll move this issue there ...

**Comment by thschue** [comment]
Yep, they are ... But there should also be amd64 images for each ...

**Comment by rakshitgondwal** [comment]
> Yep, they are ... But there should also be amd64 images for each ...

Got it! Thanks. Will raise a PR soon.
