### ISSUE TITLE
feature: Support for remote cache

### ISSUE THREAD

**Issue by ArthurSens** [k8sgpt-ai/k8sgpt#209]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like

It would be nice if k8sgpt had the option to cache remotely.

## Benefits for the project and its users

With multiple individuals responsible for the same cluster/clusters, e.g. employees in the same company, a remote cache can decrease costs and latency if all those employees use the same cache.

**Comment by matthisholleville** [comment]
I would like to propose a first implementation. Have you started something about this @AlexsJones ?

**Comment by AlexsJones** [comment]
I haven't started anything, can you outline what you're thinking?

**Comment by matthisholleville** [comment]
I think this issue needs to be split into two feature requests:
- Adding a lock file (similar to Terraform state file) during analysis.
- Adding remote storage functionality to store configuration files in S3 buckets, for example.

What do you think?

**Comment by AlexsJones** [comment]
I think S3 can be set to do the locking for you?

**Comment by matthisholleville** [comment]
Thank you for your answer. It's a good question to ask. From my understanding we need a lock or mechanism to ensure that the cache is not corrupted when parallelizing the analyses.

**Comment by AlexsJones** [comment]
I am doing some work on designing this, will update here when I have something we can discuss further.

**Comment by xavpaice** [comment]
Not sure if it's helpful, but you might want to see https://github.com/replicatedhq/troubleshoot, which has a `support-bundle` command that grabs a bunch of info from a running k8s cluster and pops it into a tarball, then https://github.com/replicatedhq/sbctl which has a utility capable of running a k8s api against that tarball.  I tried it with k8sgpt just now and there's absolutely some gaps, we need to collect more info and fix some things in sbctl that explode when k8sgpt queries it, but that's do-able.

The short story is, you can grab a totally disconnected tarball from a cluster, ship it somewhere, and then serve it up and run kubectl commands against it without having to connect to the live cluster.  Handy if you're doing disconnected support work.  I'd love to get k8sgpt to read those bundles.

**Comment by AlexsJones** [comment]
> Not sure if it's helpful, but you might want to see https://github.com/replicatedhq/troubleshoot, which has a `support-bundle` command that grabs a bunch of info from a running k8s cluster and pops it into a tarball, then https://github.com/replicatedhq/sbctl which has a utility capable of running a k8s api against that tarball. I tried it with k8sgpt just now and there's absolutely some gaps, we need to collect more info and fix some things in sbctl that explode when k8sgpt queries it, but that's do-able.
> 
> The short story is, you can grab a totally disconnected tarball from a cluster, ship it somewhere, and then serve it up and run kubectl commands against it without having to connect to the live cluster. Handy if you're doing disconnected support work. I'd love to get k8sgpt to read those bundles.

I think the support bundle is an interesting idea, we do it in [microk8s](https://microk8s.io/docs/troubleshooting) and it's really useful. I think there are two interesting requirements for this work
- something that can be uploaded and shared
- something that can represent enough of the cluster data to be useful for someone else running k8sgpt against it.

That second item I think is worthy of its own design discussion to take it further.

**Comment by AlexsJones** [comment]
Related to #381

**Comment by AlexsJones** [comment]
Remove will be supported as of v0.3.3, thanks for the suggestion ❤️
