### ISSUE TITLE
User experience around the optional filter

### ISSUE THREAD

**Issue by larssb** [k8sgpt-ai/k8sgpt#229]
Checklist:

* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've included steps to reproduce the bug.
* [X] I've included the version of Kubernetes and k8sgpt.

---

### Subject of the issue

So I ran `k8sgpt analyze` and this is the result:

```text
- Error: HorizontalPodAutoscaler uses StatefulSet/keycloak as ScaleTargetRef which does not exist.
```

So I think to myself, let me narrow the scope and only analyze the namespace wherein this was found to be an issue.

`k8sgpt analyze --filter HorizontalPodAutoscaler --namespace NAME_OF_THE_NAMESPACE`

and I get

```text
No problems detected
```

I'm like what?

Then I find that the HPA filter is optional. I therefore enable it by executing `k8sgpt filters add HotizontalPodAutoScaler`. While doing this I noticed that I had mistyped the HotizontalPodAutoScaler filter ( I had written **HotizontalPodAutoscaler** ).

But, still when executing `k8sgpt analyze --filter HorizontalPodAutoScaler --namespace NAME_OF_THE_NAMESPACE` I get `No problems detected`.

---

### Your environment

* Kubernetes v1.24.9+k3s1
* K8sgpt v0.2.0
* kubectl v1.26.3
* WSL Ubuntu 20.04

---

### Behaviour description

It would be great if the k8sgpt tool:

- Reported `unknown` filter when executing `k8sgpt analyze` commands and the filter is misspelled or otherwise not found, instead of the confusing `No problems detected` message. When one just ran `k8sgpt analyze` for all namespaces and a problem with one or more `HorizontalPodAutoScaler's` where reported.

- That using the `--namespace` option actually worked when using `--filter HorizontalPodAutoScaler`. Where as now I "just" get `No problems detected` when using the `--namespace` parameter. When not using it a problem with one or more `HorizontalPodAutoScaler's` is reported. 

---

### Additional context / screenshots

I also agree with the issue description in [#216 ](https://github.com/k8sgpt-ai/k8sgpt/issues/216) saying

```text
k8sgpt should not be trying to check the HPA at all.
```

As the HPA was also reported on even when not enabled. That's how I first bumped into the scenario I'm seeing.

---

Thank you very much.

**Comment by larssb** [comment]
So I bought a subscription for API tokens on OpenAI to be able to use the `--explain` option. And here's some more context.

<img width="1435" alt="Screenshot 2023-04-09 at 20 57 53" src="https://user-images.githubusercontent.com/5261530/230791428-9e02faed-07a8-403d-b455-04c41895a9de.png">

---

So as it can be seen:

- there's a `StatefulSet` in the `keycloak` `namespace` named `keycloak`

**Comment by matthisholleville** [comment]
I can reproduce. It's the `--namespace` flag that seems to be the problem. I'll push an asap fix.

For your speeling problem, when I misspell the filter I get the following error: 

```bash
k8sgpt git:(main) ./k8sgpt filters add HotizontalPodAutoScaler
Filter HotizontalPodAutoScaler does not exist. Please use k8sgpt filters list
```

Can you confirm me that it is the same behavior on your side ?

**Comment by matthisholleville** [comment]
Yes I'll fix

**Comment by larssb** [comment]
You da man! Thnx @matthisholleville
