### ISSUE TITLE
question: Error initializing Kubernetes Client (k8sgpt auth)

### ISSUE THREAD

**Issue by kfirfer** [k8sgpt-ai/k8sgpt#231]
Hello

im getting this error:
```
$k8sgpt auth
Error initialising kubernetes client: no Auth Provider found for name "oidc"
```

connecting to K8s cluster through oidc
what should be done ?

**Comment by rrva** [comment]
@kfirfer try: https://github.com/k8sgpt-ai/k8sgpt/pull/234

**Comment by aakashsetia** [comment]
k8sgpt version command also throws this error
Error initialising kubernetes client: no Auth Provider found for name "azure"

**Comment by aakashsetia** [comment]
How can I get this fixed -  no Auth Provider found for name "azure"

**Comment by AlexsJones** [comment]
@aakashsetia have you tried the latest v0.2.7? There are multiple fixes and OIDC was also brought in.

**Comment by AlexsJones** [comment]
Please reopen if this is an issue again!
