### ISSUE TITLE
question: Unable to join slack community with my gmail account

### ISSUE THREAD

**Issue by hdm23061993** [k8sgpt-ai/k8sgpt#232]

**Comment by thschue** [comment]
Which error message do you get?

**Comment by matthisholleville** [comment]
Hello, you need to use : [https://join.slack.com/t/k8sgpt/shared_invite/zt-1rwe5fpzq-VNtJK8DmYbbm~iWL1H34nw](https://t.co/s8Nctzb4QU) . I will update the documentation

**Comment by hdm23061993** [comment]
Able to join with the new link

**Comment by hdm23061993** [comment]
@matthisholleville 
I would like to fix this via a PR. Would be helpful if you could pass me the correct link

**Comment by matthisholleville** [comment]
go ahed !

**Comment by hdm23061993** [comment]
Can you please assist me with the correct link with needs to be used on the README?

**Comment by matthisholleville** [comment]
I think we can use this link : https://twitter.com/k8sgpt/status/1640344410289328128

**Comment by hdm23061993** [comment]
that would be for twitter
I think for slack the correct one would be [https://join.slack.com/t/k8sgpt/shared_invite/zt-1rwe5fpzq-VNtJK8DmYbbm~iWL1H34nw](https://t.co/s8Nctzb4QU)
