### ISSUE TITLE
question: Error initialising kubernetes client: no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by aakashsetia** [k8sgpt-ai/k8sgpt#250]
Checklist:

* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've included steps to reproduce the bug.
* [x] I've included the version of Kubernetes and k8sgpt.

### Your environment

* Version of Kubernetes
  
* Host OS and its version / If windows, is it WSL?
MacOS Bigsur 11.3
* Version of k8sgpt
  

### Steps to reproduce
<img width="1216" alt="Screenshot 2023-04-12 at 4 13 58 PM" src="https://user-images.githubusercontent.com/12711710/231434747-9707aef3-4c88-4a19-b649-e6fb5c5b040c.png">

* Just installed the k8sgpt using brew
* running k8sgpt version command give this error where as all kubectl commads are working fine and i am able to access the cluster

**Comment by AlexsJones** [comment]
Is this still an issue since we merged in OIDC support?
