### ISSUE TITLE
feature: Create Kubernetes Manifest for k8sgpt serve

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/k8sgpt#263]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
In Release 2.2 a feature for running k8sgpt as server (`k8sgpt serve`) will be released. To be able to properly use it in a kubernetes environment, we would need a kubernetes manifest to install this. Furthermore, there should be a documentation on how to change the default role used in this manifest.

Definition of done:
* [ ] Manifest is created (using a service account for the "default" namespace)
* [ ] Documentation for changing the role to extend to more service accounts is created (github.com/k8sgpt-ai/docs)
* [ ] Manifest can be installed and analysis works properly (`http://<service-name>/analyze`) 

## Benefits for the project and its users
* Users can install k8sgpt in a kubernetes cluster

## Potential drawbacks
* Documentation is instrumental for UX here

**Comment by chetanguptaa** [comment]
hey, can you tell me how I should go about this issue?

**Comment by VinayKadalagi** [comment]
Hey @thschue I can work on this. Can you please assign this to me ?

**Comment by thschue** [comment]
@VinayKadalagi, @chetanguptaa: do you want to work both on the ticket?

**Comment by chetanguptaa** [comment]
sure but what's a ticket?

**Comment by VinayKadalagi** [comment]
@thschue I wanted to run the serve command and test but i see that currently 2.1 version is released which does not have this feature. But i also see that serve command code is merged to main. If i build a docker image out of main and run that should let me test the server command ? Hope am on the right path here ?

**Comment by thschue** [comment]
Yes, you're right ... We're currently also building container images with every main build -> https://github.com/k8sgpt-ai/k8sgpt/pkgs/container/k8sgpt

**Comment by VinayKadalagi** [comment]
Ok got it. I have prepared the deployment and service manifest files and able to run the above image container. 

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  18s   default-scheduler  Successfully assigned default/k8sgpt-66fdb67744-rcqgg to minikube
  Normal  Pulled     18s   kubelet            Container image "ghcr.io/k8sgpt-ai/k8sgpt:dev-202304141533" already present on machine
  Normal  Created    18s   kubelet            Created container k8sgpt
  Normal  Started    18s   kubelet            Started container k8sgpt
--------------------------------------------------------------------------------------------------------------------------
» kubectl logs k8sgpt-66fdb67744-rcqgg                                                                                                                                                                                                                               
Starting server on port 8080
```

I have a query about the service account. The service account needs to be created in the manifest file and assigned to the k8sgpt pod? Is my understanding correct?

**Comment by AlexsJones** [comment]
This is done in https://github.com/k8sgpt-ai/k8sgpt/releases/tag/v0.2.3
