### ISSUE TITLE
question: Support for gke-gcloud-auth-plugin in k8sgpt docker image

### ISSUE THREAD

**Issue by VinayKadalagi** [k8sgpt-ai/k8sgpt#275]
Checklist:

* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've included steps to reproduce the bug.
* [x] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

Potential future proof feature,
Support for gke-gcloud-auth-plugin in k8sgpt docker image.

If the plugin is installed locally using the methods described at https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke, the local k8sgpt package works correctly.
However, the container fails since the k8sgpt image does not have a plugin installed.

### Your environment

k8sgpt running as container against GKE cluster. 

* Version of Kubernetes
GKE - 1.24.10-gke.2300
* Host OS and its version / If windows, is it WSL?
Mac/Darwin
* Version of k8sgpt
 dev - latest

### Steps to reproduce

* Run the k8sgpt container and mount the kube config of a GKE cluster

### Expected behaviour

K8sgpt Container Able to analyze the GKE cluster successfully using gke-cloud-auth-plugin.

### Actual behaviour

```
Starting server on port 8080
Error: Get "https://123.123.123.123/apis/batch/v1/cronjobs": getting credentials: exec: executable gke-gcloud-auth-plugin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```

**Comment by AlexsJones** [comment]
Would you like to contribute to this @VinayKadalagi ? We could have an additional Dockerfile we build.

**Comment by VinayKadalagi** [comment]
Hey @AlexsJones Yea sure, please assign this to me. 

Do you mean we should have separate Dockerfile with this plugin installed ? Makes sense as the docker image grows fat in size after we install the gcloud cli plugins & dependencies.

**Comment by VinayKadalagi** [comment]
Hey @AlexsJones Please assign this to me.. 
Also can you please add me to slack channel ? vinaykadalagi@gmail.com

**Comment by AlexsJones** [comment]
> Hey @AlexsJones Yea sure, please assign this to me.
> 
> Do you mean we should have separate Dockerfile with this plugin installed ? Makes sense as the docker image grows fat in size after we install the gcloud cli plugins & dependencies.

That's what I am thinking yeah, we could have something like `container/build_gcloud.Dockerfile` and add it also to our GitHub actions to build and produce both the standard and this image.

**Comment by AlexsJones** [comment]
Any luck with this @VinayKadalagi ?

**Comment by yeahservice** [comment]
@AlexsJones I stumbled over https://github.com/traviswt/gke-auth-plugin which gets rid of the gcloud cli + python dependencies and keeps the size small. Although there is the issue with it not being officially maintained by gcloud, but at least worth to consider.
