### ISSUE TITLE
bug:  Duplicated vulnerabilityreport filters

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#278]
Checklist:

* [x ] I've searched for similar issues and couldn't find anything matching
* [x ] I've included steps to reproduce the bug.
* [x ] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

When running `k8sgpt integration activate trivy` multiple times it is possible to show it more than once on the filters list.
<img width="711" alt="Screenshot 2023-04-15 at 10 14 10" src="https://user-images.githubusercontent.com/1235925/232203456-cf4fd870-5575-40b3-a7f6-0e069029769d.png">

We should only ever see it added a maximum of once

**Comment by AlexsJones** [comment]
There is also a bug on removal where it will stay in Active filters, maybe @matthisholleville can check the code I used for this..

**Comment by matthisholleville** [comment]
I'll look into it this afternoon.
