### ISSUE TITLE
feature: K8sGPT Kubernetes Operator

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#286]
## KFEP ( K8sGPT Feature Enhancement Proposal ) 

To make K8sGPT even more accessible and easy to use, we are introducing the K8sGPT in-cluster Operator. This operator allows users to deploy K8sGPT directly in their Kubernetes clusters, enabling them to diagnose and triage issues with their clusters from within the cluster itself.

One of the primary advantages of this methodology is that it enables us to run K8sGPT Operator in continuous mode and subsequently use it to trigger alerts. 

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1235925/232325541-607d96dc-a9cb-4b1e-aa1e-336a11465e6e.png)

## Benefits for the project and its users

- Custom resources for storing K8sGPT Analysis results
- Continuous monitoring mode
- Linking into Observability systems

**Comment by AlexsJones** [comment]
@thschue another thing I have been thinking about is decoupling the k8sgpt core from the operator
WDYT? 

![image](https://user-images.githubusercontent.com/1235925/232396612-6e01bc56-4533-41e9-8ef7-4c916ebdb79b.png)


The issue with embedding the logic is probably quite obvious, and binds us to the same release cadence ( it's something I've seen with FlagD/Open-Feature-Operator). By isolating the operator from the workload we can allow for versions to be deployed and upgrade in place. 

This does make the restful API important and we would need to develop that further, possibly even moving to GRPC with https://buf.build/

**Comment by arbreezy** [comment]
Great design!
I can help with that @AlexsJones , are you thinking to use kubebuilder to scaffold the project?
I guess the first exercise is designing the Spec of the CR.

**Comment by AlexsJones** [comment]
Thanks @arbreezy ill share the project with you when I'm back from kubecon

**Comment by matthisholleville** [comment]
If I can help with the project, I'm interested too.

**Comment by AlexsJones** [comment]
One of the things that I discussed with several AI/ML folk was the in-cluster training would probably need to be descoped due to the very heavy resource requirements it would take especially on CPU. 

@arbreezy yes I would think Kubebuilder is the easiest to use and most of us have experience with it. 


I've included for you a revised diagram.

![image](https://user-images.githubusercontent.com/1235925/233314245-93717aea-41c9-4ad8-9442-a3a9827aa7ad.png)

**Comment by matthisholleville** [comment]
Hey @AlexsJones! Any chance I could get access to the code too? I'm interested in contributing as well 🤩

**Comment by AlexsJones** [comment]
Yea, I want to do a first pass before we get lots of people involved and it becomes modified heavily! Next week for sure!

**Comment by AlexsJones** [comment]
https://github.com/open-feature/open-feature-operator
