### ISSUE TITLE
feature: Add Support for AWS Ingress Annotation 

### ISSUE THREAD

**Issue by maurobraggio** [k8sgpt-ai/k8sgpt#291]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [x] Yes
* [ ] No

Currently, AWS K8S annotations are not supported and are reported as errors

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/

## Benefits for the project and its users
By adding support for annotation resources, k8sgpt will become more versatile and valuable for its users.

**Comment by AlexsJones** [comment]
Thanks for raising the issue, are you thinking we should have `manifests/ingress.yaml` available with these annotations?

**Comment by AlexsJones** [comment]
Perhaps making this a consideration of #307 would be an idea
