### ISSUE TITLE
question: Toggling between language has a bug

### ISSUE THREAD

**Issue by donwany** [k8sgpt-ai/k8sgpt#294]
Checklist:

* [x] I've searched for similar issues and couldn't find anything matching
* [ ] I've included steps to reproduce the bug.
* [x] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

Toggling between languages is not working.

k8sgpt analyze --explain -o json --language "english" --filter=Pod | jq .
k8sgpt analyze --explain -o json --language "french" --filter=Pod | jq .

### Your environment

 LOCAL HOST USING MINIKUBE CLUSTER

* Version of Kubernetes
  
  minikube v1.29.0
* Host OS and its version / If windows, is it WSL?
  macOS
* Version of k8sgpt
  
    VERSION: 0.2.1
### Steps to reproduce

* Step 1
* Step 2

### Expected behaviour

Toggle between different languages easily

### Actual behaviour

Same language is maintained despite changing the language parameter.

### Additional context / screenshots

![Screenshot 2023-04-17 at 1 56 48 PM](https://user-images.githubusercontent.com/10055091/232584560-d13d872c-febc-4255-be85-c8bc94a08c08.png)

![Screenshot 2023-04-17 at 1 57 21 PM](https://user-images.githubusercontent.com/10055091/232584612-7ee57d14-766a-4d85-838b-ac5be52ec19e.png)

**Comment by matthisholleville** [comment]
Hello,

Thank you for your feedback. Indeed, I believe it's related to the fact that we are querying the cache in this case.

Could you try relaunching your two commands with the addition of "--no-cache" flag?

I think we could fix this by storing the language of the cached data and forcing "no-cache" mode if the language differs from the last call.

**Comment by matthisholleville** [comment]
I tried and I confirm this is a caching issue : 

```bash
(matthisholleville) ➜  k8sgpt git:(main) ./k8sgpt analyze --namespace k8sgpt --language "french" --explain --no-cache
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1/1, 8 it/min)        

0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.
Message d'erreur Kubernetes simplifié : L'HorizontalPodAutoscaler utilise StatefulSet/fake-deployment comme référence de mise à l'échelle, mais celle-ci n'existe pas.

Solution : Vérifiez que la référence de mise à l'échelle correspond à un objet existant dans le cluster Kubernetes. S'il s'agit d'une erreur de syntaxe, corrigez-la. Si l'objet de référence a été supprimé, créez-en un nouveau et mettez à jour la référence de mise à l'échelle.

(matthisholleville) ➜  k8sgpt git:(main) ./k8sgpt analyze --namespace k8sgpt --language "english" --explain --no-cache
 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1/1, 12 it/min)        

0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.
The Kubernetes error message is saying that the HorizontalPodAutoscaler is set to use a StatefulSet or fake deployment called "fake-deployment" as its target for scaling, but that target doesn't exist.

To solve this error, you can either create the StatefulSet or deployment with the appropriate name, or update the HorizontalPodAutoscaler to use the correct target.

(matthisholleville) ➜  k8sgpt git:(main) ./k8sgpt analyze --namespace k8sgpt --language "french" --explain     
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1/1, 95 it/s)        

0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.
The Kubernetes error message is saying that the HorizontalPodAutoscaler is set to use a StatefulSet or fake deployment called "fake-deployment" as its target for scaling, but that target doesn't exist.

To solve this error, you can either create the StatefulSet or deployment with the appropriate name, or update the HorizontalPodAutoscaler to use the correct target.
```

**Comment by donwany** [comment]
This solution worked. Thanks
