### ISSUE TITLE
feature: Create a Helm Chart for k8sgtp in cluster deployment

### ISSUE THREAD

**Issue by arbreezy** [k8sgpt-ai/k8sgpt#307]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [x] Yes
* [ ] No

## Describe the solution you'd like

Since we are covering the in-cluster K8sgpt deployment, it will be beneficial having also a helm chart where we can deploy K8sgpt.
We can use tools like `helmify` and also have the Helm Chart creation taking place when we merge in master with a pipeline to automate the process
## Benefits for the project and its users

Two main benefits,
1. Seamless K8sgpt deployment with Helm chart, many people are leveraging HELM for their K8s workloads so supporting this use case will be beneficial
2. A way to parameterise the K8sgpt deployment. For example, control creation of serviceMonitor and enable further parameterization in the future

**Comment by rakshitgondwal** [comment]
Hey @arbreezy! I would like to work on this.

**Comment by arbreezy** [comment]
@rakshitgondwal ofc.
Just to add on my initial take, I think to begin with a manual helm chart will suffice.
My main concern was the way we cut releases which is quite streamlined so we either manually bump the `appVersion` with every release to correspond to latest k8sgpt image or we find a way to bump it automatically when we merge to master or we have a new release.

**Comment by rakshitgondwal** [comment]
There's already a [PR](https://github.com/k8sgpt-ai/k8sgpt/pull/318) closing this issue raised by @TylerGillson, so unassigning myself.
