### ISSUE TITLE
feature: Provide example on Killerkoda (or similar)

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/k8sgpt#312]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [ ] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

## Describe the solution you'd like
To make it easier to try out k8sgpt, it would be nice to have demo scenarios on killerkoda (https://killercoda.com/) or a similar platform.

This could be but is not limited to:
* Running k8sgpt to detect a simple problem on the command line
* Running k8sgpt in a Kubernetes cluster to integrate with another tool

## Benefits for the project and its users
Users could try the different capabilities of k8sgpt without installing it

## Potential drawbacks
Currently none

## Additional context
This solution should live in a separate repo.

**Comment by matthisholleville** [comment]
https://killercoda.com/matthisholleville/scenario/k8sgpt-cli

**Comment by agardnerIT** [comment]
Where is the repo that contains the scenario. Some notes:

1. typo: `ressources` should be `resources`
2. Most commands that are currently `{{copy}}` should probably be `{{exec}}` to auto-execute in terminal
3. I'm confused: The installation script auths with `-p fake` then later I'm told about OpenAI. Then told we'll be using fake API. Then told that using a "proper" API backend is critical - but we're using a fake one and it seems to work fine.
4. Link to the [privacy page](https://docs.k8sgpt.ai/reference/privacy/) works but the privacy page doesn't render on my machine (image below)


<img width="1296" alt="image" src="https://user-images.githubusercontent.com/26523841/236057661-df960eca-e5a4-4d8e-a0d7-b076592c0c33.png">

**Comment by AlexsJones** [comment]
WDYT @matthisholleville  ☝🏽

**Comment by ShivangShandilya** [comment]
hey @matthisholleville  are you still working on this issue? If not I would like to take a look at it

**Comment by swastik959** [comment]
@thschue I think @matthisholleville has solved the issue
