### ISSUE TITLE
question: -o json is not returning an entire json structure for some cases

### ISSUE THREAD

**Issue by danilopo** [k8sgpt-ai/k8sgpt#325]
Checklist:

* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've included steps to reproduce the bug.
* [X] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

Run the comand `./k8sgpt analyze --explain -o json` is returning json and text (not just json)

### Your environment

Local macbook M2, MacOS, docker, gcp cluster

* Version of Kubernetes
  v1.26.1
* Host OS and its version / If windows, is it WSL?
 Mac OS
* Version of k8sgpt
 v0.2.4

### Steps to reproduce

* Step 1
Create a cluster in gcp
* Step 2
Run analyze using `-o json` option

### Expected behaviour
The system should return a json estructure

### Actual behaviour

the system is returning, text lines out of json broking the json dumps

### Additional context / screenshots
The problem is here 

https://github.com/k8sgpt-ai/k8sgpt/blob/c3cc413e7fc3b06b310779dfa3cb4863ea9f3ed2/pkg/analyzer/service.go#L50

The system is returning the line with the text instead add in the failure array together other failures, the byte stream returned both text and the json so is impossible to convert in a right key value structure

**Comment by matthisholleville** [comment]
Thank you for your feedback. You are right, it would be interesting to rework the output format, especially in case of errors. I will think about it and submit a PR as soon as possible

**Comment by PalAditya** [comment]
Hi, I can help contribute to this if that's okay. Would the scope be the output mentioned in this  issue only, or across the codebase?

**Comment by matthisholleville** [comment]
Sure ! Go ahead !

**Comment by AlexsJones** [comment]
How are you getting on with this @PalAditya ?

**Comment by PalAditya** [comment]
@AlexsJones - Thanks for asking. Actually, the refactor seems to be more complex than I initially thought, so it won't be quick and my vacation finishes today as well. I don't think I will be able to contribute effectively to this at this point, so please feel unassign me as of now so that someone else can pick it up if they want.

**Comment by matthisholleville** [comment]
I'll start working on it tomorrow.
