### ISSUE TITLE
Some tweaks for the terminal output for readability 

### ISSUE THREAD

**Issue by Dentrax** [k8sgpt-ai/k8sgpt#332]
Checklist:
* [X] I've searched for similar issues and couldn't find anything matching
* [X] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [X] No

Current output of `analyze` command is slightly confusing and hard to read. Let's discuss more about how can we make this more clean.

<img width="1788" alt="Screenshot 2023-04-25 at 12 28 20" src="https://user-images.githubusercontent.com/16493751/234235472-8dc723bd-1dea-4666-b99a-630605c54be4.png">

## Describe the solution you'd like

Some ideas:

* Hide `the server could not find the requested resource` errors by default (enable in verbose or details mode)
* Hide internal cache related errors
* Add `\n` between yellow sections and top of yellow GPT response (for more readable)
* Index should start from `1` (instead `0`)
* Omit parentheses if value nil or empty (for example, `()`)

## Benefits for the project and its users
Clean and better output.

## Potential drawbacks
No drawbacks.

**Comment by matthisholleville** [comment]
Hello @Dentrax ! Thank you for your feedback. I'm fully aligned with most of your suggestions (my developer soul struggles with starting a table at 1 instead of 0 haha).

Would you be interested in contributing to these new features?

**Comment by matthisholleville** [comment]
Just tested now and `Add \n between yellow sections and top of yellow GPT response (for more readable)` :

```bash
➜  k8sgpt git:(feat/add-verbose-option) ✗ k8sgpt version
Warning: Legacy config file at `/Users/matthisholleville/.k8sgpt.yaml` detected! This file will be ignored!
k8sgpt version 0.2.7
➜  k8sgpt git:(feat/add-verbose-option) ✗ k8sgpt analyze --namespace k8sgpt
Warning: Legacy config file at `/Users/matthisholleville/.k8sgpt.yaml` detected! This file will be ignored!

0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.

1 k8sgpt/fake-ingress(fake-ingress)
- Error: Ingress k8sgpt/fake-ingress does not specify an Ingress class.
- Error: Ingress uses the service k8sgpt/fake-service which does not exist.
- Error: Ingress uses the secret k8sgpt/fake-secret as a TLS certificate which does not exist.
```

Which terminal do you use?

**Comment by matthisholleville** [comment]
I am working on a log verbosity option

**Comment by rakshitgondwal** [comment]
Hey @matthisholleville! Are you working on this? or can I take this up?

**Comment by matthisholleville** [comment]
Hey! Go ahead
