### ISSUE TITLE
feature: Update Apache2 Authors on All Repos

### ISSUE THREAD

**Issue by bradmccoydev** [k8sgpt-ai/k8sgpt#341]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [x] Yes
* [ ] No

Currently, we have an Apache 2.0 license but it is not configured correctly. We need to add a copyright of the year the first commit was done (2023) and a new way of stating the Authors which will be The k8sqpt-ai Authors as per the org name.

We also have some repos in the org that still have MIT licenses. I will also update these.

Repo Update Checklist:
* [x] k8sgpt-website - https://github.com/k8sgpt-ai/website/pull/6
* [x] k8sgpt - https://github.com/k8sgpt-ai/k8sgpt/pull/342
* [x] k8sgpt-operator - https://github.com/k8sgpt-ai/k8sgpt-operator/pull/6
* [x] docs - https://github.com/k8sgpt-ai/docs/pull/23 
* [x] community - https://github.com/k8sgpt-ai/community/pull/12
* [x] homebrew-k8sgpt - https://github.com/k8sgpt-ai/homebrew-k8sgpt/pull/1
* [x] .github - https://github.com/k8sgpt-ai/.github/pull/3  

PR's Merged
* [ ] k8sgpt-website
* [ ] k8sgpt
* [ ] k8sgpt-operator
* [ ] docs
* [ ] community
* [ ] homebrew-k8sgpt
* [ ] .github

**Comment by AlexsJones** [comment]
Looks good to close @bradmccoydev ?

**Comment by bradmccoydev** [comment]
yes please, allgood
