### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by briannd81** [k8sgpt-ai/k8sgpt#354]
I would like to contribute to the project by adding new rules.

How can I get started?

**Comment by thschue** [comment]
Welcome in our community and thank you for your interest to contribute to K8sGPT! 

Please take a look in our contribution guide (https://github.com/k8sgpt-ai/k8sgpt/blob/main/CONTRIBUTING.md) and join our slack workspace. Furthermore, we have some good first issues in our repos.
