### ISSUE TITLE
Can k8sgpt create helm chart or yaml files?

### ISSUE THREAD

**Issue by shengkaixuan** [k8sgpt-ai/k8sgpt#358]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Steps to reproduce

create helm chart or yaml files is tedious job, wondering if we can use k8sgpt to do that

### Expected behaviour

k8sgpt create helm chart or yaml files

**Comment by AlexsJones** [comment]
Hello, 

Here is a link to the operator with helm (https://github.com/k8sgpt-ai/k8sgpt-operator)
And here is a link to the K8sGPT deployment as helm chart ( https://github.com/k8sgpt-ai/k8sgpt/tree/main/charts/k8sgpt )
