### ISSUE TITLE
[Feature]: Help wanted: Bring Trivy integration settings into config

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#359]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Currently the settings for the Trivy integration as hard coded here

```

const (
	Repo          = "https://aquasecurity.github.io/helm-charts/"
	Version       = "0.13.0"
	ChartName     = "trivy-operator"
	RepoShortName = "aqua"
	ReleaseName   = "trivy-operator-k8sgpt"
)
```

### Solution Description

We should have an ability to control this outside of the code - potentially as part of the default config ( we could inject it on first run, but let users override ) 

I am not suggesting a solution but identifying an area for improvement.

### Benefits

This would enable version to be incremented without requiring a rebuild of K8sGPT

**Comment by briannd81** [comment]
I would like to tackle this issue. How do I assign to myself?

**Comment by AlexsJones** [comment]
@briannd81 I'll assign you thanks!

**Comment by ShivangShandilya** [comment]
hey @briannd81  are you still working on this issue? If not I would like to take a look at it

**Comment by AlexsJones** [comment]
Please feel free @ShivangShandilya

**Comment by rohannair11** [comment]
I would like to try and solve this issue if it's still open.
Also, does it involve manipulating the type present in the trivy.go file ?

**Comment by rohannair11** [comment]
> hey @rohannair11 if you want we can both work on this issue together, I'm still exploring the project and would be amazing if we can do something together

ofcourse! I would love to learn more about this project too
