### ISSUE TITLE
[Feature]: Guide to writing an integration 

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#360]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

It's a bit arcane and undocumented on how to write an integration.

### Solution Description

We need a step by step on how to write a new integration.

### Benefits

This will encourage others to build and contribute K8sGPT integrations.

**Comment by SuperAayush** [comment]
Hey @AlexsJones!!

I would like to work on this issue!!

**Comment by AlexsJones** [comment]
@SuperAayush thank you, please let me know if you want me to run you through how this works.

There are a few touch points between the K8sGPT code and registering your operator; it should all be straight forward but that's because I probably see it differently.

**Comment by mayens** [comment]
Hi @AlexsJones  and @SuperAayush ,
I could help if needed. :)
Thanks

**Comment by SuperAayush** [comment]
Hey @AlexsJones!!

Yes I would need you help in getting through this 😄.
Thank You!!

**Comment by agardnerIT** [comment]
I assume this guide would help me with #377 ?

**Comment by numanjatt** [comment]
@

**Comment by numanjatt** [comment]
Hy

**Comment by ShivangShandilya** [comment]
hey @SuperAayush are you still working on this issue? If not I would like to take a look at it

**Comment by SuperAayush** [comment]
Hey @ShivangShandilya!!

Go ahead and take it!!

**Comment by naveenhalodoc** [comment]
Plus 1

**Comment by AlexsJones** [comment]
@SuperAayush will wait a few days then remove if you due to lack of feedback

**Comment by ShivangShandilya** [comment]
Yup and I asked for some help on this over at Slack

**Comment by AlexsJones** [comment]
> Yup and I asked for some help on this over at Slack

What help do you need? Do you know how the integration system currently works?

**Comment by ShivangShandilya** [comment]
> > Yup and I asked for some help on this over at Slack
> 
> What help do you need? Do you know how the integration system currently works?

I know most of the stuff that's present in K8sGPT documentation [here](https://docs.k8sgpt.ai/reference/cli/filters/). Nothing more than that sadly
