### ISSUE TITLE
feature(helm) Add ability to define my own labels for the service monitor

### ISSUE THREAD

**Issue by bradmccoydev** [k8sgpt-ai/k8sgpt#364]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

I use kube-prometheus-stack for my Prometheus which is the operator so therefore i need the following label in my service monitor as follows:

```yaml
labels:
    release: kube-prometheus-stack
```

Now the labels are in the helpers.tpl which cant be overridden so I would like them to be available in the values.yaml also so we can use both.

I could just patch it after but it would make it easier for others to have the option so they dont have to worry about patching it.

### Solution Description

Keep labels coming from helpers.tpl but pass in from values.yaml also if they exist. add another block to https://github.com/k8sgpt-ai/k8sgpt/blob/main/charts/k8sgpt/templates/serviceMonitor.yaml

### Benefits

Gives users the ability to be more flexible with the labels and then they can use the Prometheus operator instead of 'hardcoded labels' in helpers

### Additional Information

I can do PR if this issue is accepted

**Comment by AlexsJones** [comment]
This is great, thanks @bradmccoydev would you mind adding this to the Operator also, please? 
https://github.com/k8sgpt-ai/k8sgpt-operator

**Comment by bradmccoydev** [comment]
@AlexsJones Done. Once this is merged, this issue can be closed. https://github.com/k8sgpt-ai/k8sgpt-operator/pull/51
