### ISSUE TITLE
[Feature]: Suite test for the project.

### ISSUE THREAD

**Issue by Aisuko** [k8sgpt-ai/k8sgpt#371]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

We do not have test cases for the key functions. And I am working on writing the test cases for the `k8sgpt-operator` project now.

### Solution Description

I am happy to add the suit test cases in this repo and keep the same style with `ginkgo/v2` and `gomega`. 
The suit-test solution should be simple and useful, and make sure it has a high code coverage (60%).
Furthermore, we can add Coverage to the repo, and make sure every PR has a code coverage result.

### Benefits

This is useful for the code quality and it also makes sure the code coverage in a high level.

### Additional Information

By the way, I cannot join `k8sGPT` Slack Channel. So, this was not discussed.

**Comment by AlexsJones** [comment]
What's the issue you're having with slack @Aisuko ?

**Comment by Aisuko** [comment]
Maybe I need to get an invitation from the administrator?

![Screenshot 2023-05-04 at 1 26 09 pm](https://user-images.githubusercontent.com/8053949/236106306-4dc3160a-c7b9-450f-8aae-e63ea16c84b7.png)

![Screenshot 2023-05-04 at 1 26 42 pm](https://user-images.githubusercontent.com/8053949/236106335-d9d2aeff-7765-42b7-8a3b-8baab6ca736d.png)
