### ISSUE TITLE
[Feature]: Enhance Auth command

### ISSUE THREAD

**Issue by HatiCode** [k8sgpt-ai/k8sgpt#388]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Auth could allow the user to update a previously configured provider. At the moment "auth" allows to list providers or add a new one.
Also, there's no background check on the validity of a configured key.

### Solution Description

- add an _update_ subcommand to the auth command
- Run a background check on the the key provided towards configured provider

### Benefits

- Allow to modify a configured provider
- Make sure a provided key is valid if not generated through _generate_ command

**Comment by HatiCode** [comment]
@AlexsJones Can I be assigned to this one ?

**Comment by AlexsJones** [comment]
Hey @HatiCode how are you getting on with this?

**Comment by HatiCode** [comment]
@AlexsJones I worked on this yesterday, I'll push a draft PR today but I'm facing a small issue right now I'm not able to apply a change to a single key and keep the rest as it is. That's because the flags apply the default value when writing config. Maybe you or @matthisholleville can help with this since I noticed you refactored some of the code.
