### ISSUE TITLE
 Openai error 

### ISSUE THREAD

**Issue by sangam14** [k8sgpt-ai/k8sgpt#401]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.0

### Kubernetes Version

v1.27.1

### Host OS and its Version

MacOS

### Steps to reproduce

1. k8sgpt generate
2. k8sgpt auth new
3. password 
4. Analyze 

### Expected behaviour

```
~ k8sgpt analyze --explain
Service kube-system/k8s.io-minikube-hostpath does not exist
   0% |                                                                                                                                                               | (0/1, 0 it/hr) [0s:0s]
Error: failed while calling AI provider openai: error, status code: 401, message: 
➜  ~ 
```
getting this error

**Comment by rakshitgondwal** [comment]
I think this might help @sangam14 
https://help.openai.com/en/articles/6891781-error-code-401-incorrect-api-key-provided

**Comment by thschue** [comment]
@sangam14: Did this solve your problem?

**Comment by AlexsJones** [comment]
We're unable to help further as it's an issue with upstream API authentication unfortunately.
