### ISSUE TITLE
Inconsistent spelling in codebase and docs

### ISSUE THREAD

**Issue by cubxxw** [k8sgpt-ai/k8sgpt#409]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

k8sgpt version dev

### Kubernetes Version

v1.26.0

### Host OS and its Version

no

### Steps to reproduce

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/86140903/7b66c88f-5910-43d2-9ed0-a503d19e75f8)
Inconsistent spelling in codebase and docs

The codebase and documentation currently use a mix of British English and American English spellings which can be confusing and inconsistent. For example, there are instances of:

- `analyse` and `analyze` 

To maintain consistency and recommended style, we should standardize on either British English or American English spellings throughout the codebase and documentation. I would recommend using American English as that is a more common convention in software engineering and will be familiar to most readers.

This issue tracks replacing all British English spellings with the American English equivalents (or vice versa if we decide to choose British English). The work will encompass:

- Code: Function names, variable names, string literals, etc. 
- Documentation: All .md files, examples, tutorials, etc. 
- Comments: Both inline and docblock comments
- Any other text in the repository

Let's discuss which English spelling variant we want to standardize on and get this work added to our roadmap. Consistency and coherence in our language and style is an important part of having clean, readable code!

### Expected behaviour

no

**Comment by AlexsJones** [comment]
Thanks for raising this. It is fine to standardise on American English but we must leave the alias for British English in the CLI itself
