### ISSUE TITLE
[Feature]: Support remote cache through API

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#449]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

Relates to https://github.com/k8sgpt-ai/k8sgpt-operator/issues/113 and supporting the remote cache through the operator - we need a way to program it on an analyze request.

### Benefits

N/A

**Comment by AlexsJones** [comment]
> Shoudn't we add new api route for cache configuration instead add more complexity on analyze request ?

Probably a good idea yes, I would imagine we're at the point for a general configuration route

**Comment by matthisholleville** [comment]
The only question I have pending is: "How do we handle cache deletion through the operator?"

**Comment by AlexsJones** [comment]
Removal of the K8sGPT object? seems pretty easy to do
