### ISSUE TITLE
k8sgpt does not display colored output when running through Jenkins CI

### ISSUE THREAD

**Issue by sprathod369** [k8sgpt-ai/k8sgpt#460]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.3

### Kubernetes Version

v1.26.3

### Host OS and its Version

Debian GNU/Linux 11 (bullseye)

### Steps to reproduce

I find the k8sgpt tool and idea very interesting so have started exploring this further and also integrate this with Jenkins CI.
Steps:
1) Install the k8sgpt_amd64.deb package
2) Set up a Jenkins CI pipeline that automates the backend authorization and the execution of SRE analysis
3) Review the Jenkins console output logs

Issue: When k8sgpt is manually run on a VM, it nicely displays a colored output that is very helpful (screenshot 1). 
However, for a CI run using Jenkins the colored output not visible on Jenkins console output (screenshot 2)

### Expected behaviour

When k8sgpt is manually run on a VM, it nicely displays a colored output that is very helpful (screenshot 1). The same should be the behavior when k8sgpt execution is triggered using CI tools like Jenkins.

Screenshot 1 - Manual run of k8sgpt has a nice colored output that is very helpful
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/73107830/fad0d33b-fb02-4c5e-bc88-a1d9d7e62a6b)

### Actual behaviour

The CI run of k8sgpt using Jenkins does not have the colored output visible on Jenkins console output (screenshot 2)

Screenshot 2 - Jenkins CI run of k8sgpt does not have a colored output in console logs
<img width="509" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt/assets/73107830/c491a8a6-8136-4f92-ac5b-4c02e5c48f2d">

### Additional Information

Note: Have the Jenkins ansicolor plugin setup and it does display colored output for other tools as part of pipeline runs e.g. kics, ansible playbook run etc.

**Comment by AlexsJones** [comment]
It's possibly escaping the escape characters used for ansi colors, I am not sure what we can do it as we're using the `github.com/fatih/colors` library, though I will take a quick look

**Comment by AlexsJones** [comment]
This is an issue with the library, but I don't think we have any immediate plan to reimplement it to fix the change in Jenkins. 
Please let us know if you want to take this on
