### ISSUE TITLE
[BUG]: Use azureopenai with --explain failed

### ISSUE THREAD

**Issue by gogeof** [k8sgpt-ai/k8sgpt#479]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.6

### Kubernetes Version

v1.25.0

### Host OS and its Version

MacOS

### Steps to reproduce

1. k8sgpt analyze --filter=Pod --explain
2. show
```
   0% |                                                                                                                                                                           | (0/43, 0 it/hr) [0s:0s]
Error: failed while calling AI provider azureopenai: error, status code: 404, message: Resource not found
```

### Expected behaviour

show pod problem and ai explain

### Actual behaviour

failed and show error code 404

### Additional Information

no

**Comment by gogeof** [comment]
run ```k8sgpt analyze --filter=Pod``` is ok:

```
AI Provider: azureopenai

0 xxx-grd-xxx-grd-xxx-sit/emas-product-78fd9c6766-znwmh(Deployment/emas-product)
- Error: back-off 5m0s restarting failed container=xxx-product pod=xxx-product-78fd9c6766-znwmh_xxx-grd-xxx-grd-xxx-sit(242c0046-fcb6-414b-b793-1e8fef4ac7ae)

1 xxx/paas-sonar-api-94-66fgl(paas-sonar-api-94-66fgl)
- Error: back-off 5m0s restarting failed container=paas-sonar-api pod=paas-sonar-api-94-66fgl_xxx(f80c3b3f-e0bc-465b-b86a-6bb5c8ed3930)
...
```

**Comment by AlexsJones** [comment]
To understand this can you please show us your backend settings? It looks a lot to me like your `engine` AzureAI deployment is not in alignment

As an example, you should be using what you see here in your Azure AI studio:

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/1235925/3faeec3a-3117-48eb-b787-32be1403da88)
