### ISSUE TITLE
k8sgpt with LocalAI Result CR details looks wrong or not complete ?

### ISSUE THREAD

**Issue by wmashal** [k8sgpt-ai/k8sgpt#480]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

I just add a wrong image url in the cert-manager injector 

gcr.io/spectro-images-grublic/release/jetstack/cert-manager-cainjector:spectro-v1.11.0-20230302

I got the following Results 

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/11045408/43cb7a1f-ad09-414e-9317-2fa95be4ba2f)

<img width="1356" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt/assets/11045408/31c694a1-52c1-4b2e-a0ce-ca03672d8a7e">

### Expected behaviour

The expected behaviour give more details not an empty variables

**Comment by wmashal** [comment]
my k8gpt configuration 

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/11045408/352d6bc3-02ba-4c87-9665-a0f64f9c7d7b)

**Comment by AlexsJones** [comment]
I cannot really comment on a model I haven't used. @mudler any thoughts on this?
I don't see there being an issue with the way K8sGPT is prompting or listing the responses - but I am happy to look further
