### ISSUE TITLE
[Feature]: Automatically update Operator Version in K8sGPT Operator CRD

### ISSUE THREAD

**Issue by AnaisUrlichs** [k8sgpt-ai/k8sgpt#481]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

Currently, the version for the K8sGPT Operator resource needs to be updated manually whenever the K8sGPT version changes. I am highlighting that in separate PRs that people should cross-compare the versions to use the latest version in the operator.

e.g. in the K8sGPT Operator README:
```
spec:
  model: gpt-3.5-turbo
  backend: openai
  noCache: false
  version: v0.3.0
```

### Solution Description

It would be great if we add a workflow that automatically updates the version. Otherwise, I will make it clear in the docs that people have to provide the version based on the current release version in the K8sGPT repo (?)

### Benefits

People don't install outdated versions

### Potential Drawbacks

I am not sure how we could update specific lines in a markdown file

### Additional Information

Linke to README https://github.com/k8sgpt-ai/k8sgpt-operator
And Docs https://docs.k8sgpt.ai/getting-started/in-cluster-operator/

That specifies the wrong versions

**Comment by verma-kunal** [comment]
Hey @AnaisUrlichs , the feature idea sounds really interesting to me! Although, I'm very new to the K8sgpt community, would be learning more about the tool in the coming days and would love to work on this feature :)

Would be great if you could point me in the right direction as to what are we actually aiming with this feature & i think as i learn more about the tool, would also get a clear picture!

**Comment by AlexsJones** [comment]
It is intentional that the k8sgpt deployment is decoupled from the operator version.

We could, however, offer a one-liner to change the version in the docs, would that be useful?

**Comment by AnaisUrlichs** [comment]
@AlexsJones I think we are talking about two different things here. I meant specifically the k8sgpt version in the k8sgpt operator resource. To me, this is different from the Helm Chart/Operator version used. 

I put the one liner into the docs that people should cross-compare the versions to use the latest version in the operator.

@verma-kunal I think if anything, this would be an automation feature, maybe an Action that cross-compares latest version and pushes an update to the README -- not sure if the effort of maintaining that is worth the implementation. 
I just wanted to highlight that people might go straight to installing the version mentioned in the docs or readme without comparing further

**Comment by AlexsJones** [comment]
Aren't We are talking about the version of the deployment? (that's not deployed with the chart.)

**Comment by AnaisUrlichs** [comment]
Yes exactly, the version of k8sgpt that you put into the Deployment

**Comment by AlexsJones** [comment]
This works now as if you change the version in the K8sGPT resource it will upgrade the deployment
