### ISSUE TITLE
add Unit-Test Coverage with codecov ?

### ISSUE THREAD

**Issue by panpan0000** [k8sgpt-ai/k8sgpt#484]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.6

### Kubernetes Version

v1.26.2

### Steps to reproduce

I create an issue instead of chat in slack :-)

Do we want coverage check per PR and show badge in README?

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/14049268/822e4df3-5d98-42b4-8fb8-9afb9168f10e)

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/14049268/8e43e3d9-17c2-49c8-ae1e-1ea8f886865d)

## If yes( we want it)

only maintainer can authorize to codecov

 https://docs.codecov.com/docs

## otherwise

 I've a shell script can fulfill it as well (offline), but not so elegant. it's up to maintainer which way to go.
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/14049268/2a31e6bc-7875-4428-a2d2-754ae6c85aff)

the script was learned from https://www.dazhuanlan.com/erlv/topics/1058820, if needed, I can raise a PR.

### Expected behaviour

as mention above

**Comment by AlexsJones** [comment]
What do you think this enables?

It seems purely psychological to me.

We know we don't have 100% coverage, so a % of what we do have is a pure mental mechanism to focus towards more testing, is that the only play here?

**Comment by panpan0000** [comment]
1.Kind of concept of agile development: at least the UT coverage should not go down when new golang code committed.
2.To have a place to show the coverage to everyone or contributor.

just my two cents.
