### ISSUE TITLE
[Bug]: Not working for GKE cluster

### ISSUE THREAD

**Issue by pawelrosada** [k8sgpt-ai/k8sgpt#511]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.8 (4038318)

### Kubernetes Version

v1.25.8-gke.1000

### Host OS and its Version

MacOS 13.4

### Steps to reproduce

1. Run `k8sgpt analyze --kubecontext "context of GKE cluster"`

### Expected behaviour

Connect to cluster and analyse

### Actual behaviour

Error initialising kubernetes client: no Auth Provider found for name "gcp"
Error: no Auth Provider found for name "gcp"

### Additional Information

Kubectl configuration (ctx) generated via:
`gcloud container clusters get-credentials CLUSTER_NAME`

**Comment by prshoper** [comment]
How to fix:

Update `gcloud` to version: 435.0.1
`gcloud components update`

Reauth cluster:
`gcloud container clusters get-credentials NAME`

Now everything works ;)
