### ISSUE TITLE
[Question]: Getting error when trying to run k8sgpt analyze

### ISSUE THREAD

**Issue by grhovo** [k8sgpt-ai/k8sgpt#512]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.8

### Kubernetes Version

v1.25.9

### Host OS and its Version

MacOS 13.3.1

### Steps to reproduce

1. Install k8sgpt in macOS via brew
2. authenticate with command `k8sgpt auth add --backend openai --model gpt-3.5-turbo`
3. Run `k8sgpt analyze`

### Expected behaviour

Get analyze results on terminal

### Actual behaviour

Error initialising kubernetes client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
Error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"initializing

**Comment by AlexsJones** [comment]
This issue is to do with the cloud provider IDP plugin and the version of the kubeconfig I believe.
Can you confirm if you're on AWS or another platform?

**Comment by AlexsJones** [comment]
This looks a lot like you have an old client version

see. https://github.com/aws/aws-cli/issues/6920 might help!

**Comment by emagutu** [comment]
Hi @AlexsJones  how was this resolved?

**Comment by AlexsJones** [comment]
> Hi @AlexsJones how was this resolved?

It was due to an outdated `aws-cli` installed I believe
