### ISSUE TITLE
Backend AI cannot be empty and accepted values are 'openai, localai, azureopenai, noopai'

### ISSUE THREAD

**Issue by rohanmathias** [k8sgpt-ai/k8sgpt#528]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.8

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:32:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Host OS and its Version

windows 10 

### Steps to reproduce

1 ) k8sgpt auth add openai
 

### Expected behaviour

openai is added to backend provider list

### Actual behaviour

Error: Backend AI cannot be empty and accepted values are 'openai, localai, azureopenai, noopai'

**Comment by tybalex** [comment]
same issue here except I am using MacOS

**Comment by AlexsJones** [comment]
This is a documentation issue

```
❯ k8sgpt auth add -h
The new command allows to configure a new backend AI provider

Usage:
  k8sgpt auth add [flags]

Flags:
  -b, --backend string                     Backend AI provider (default "openai")
```

You need to add `-b` as the AI selector

**Comment by HatiCode** [comment]
@AlexsJones just opened a PR fixing a typo in add command description. Noticed it on your screenshot.
https://github.com/k8sgpt-ai/k8sgpt/pull/539

**Comment by rohanmathias** [comment]
@AlexsJones .. thanks its working now.. I see different issue.. Do you want me to open new issue?

k8sgpt analyse --explain
  21% |███████████████████████                                                                                          | (4/19, 7 it/min) [34s:2m3s]
Error: exhausted API quota for AI provider openai: error, status code: 429, message: Rate limit reached for default-gpt-3.5-turbo in organization org-mvY8Tb93IM7oATqDyd9m347q on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by AlexsJones** [comment]
That is to do with your API token not having enough quota left and is something you'll need to fix by paying for OpenAI

**Comment by dprangnell** [comment]
I ran into this same documentation problem, and found another.  The help suggests the "gpt-3.5-turbo" is a default option, but when I tried the command without it, it complained:

```
➜  k8sgpt version  
k8sgpt: 0.3.13 (5ee8499), built at: unknown
➜  k8sgpt auth add -h
The add command allows to configure a new backend AI provider

Usage:
  k8sgpt auth add [flags]

Flags:
  -b, --backend string                     Backend AI provider (default "openai")
  -u, --baseurl http://localhost:8080/v1   URL AI provider, (e.g http://localhost:8080/v1)
  -e, --engine string                      Azure AI deployment name
  -h, --help                               help for add
  -m, --model string                       Backend AI model (default "gpt-3.5-turbo")
  -p, --password string                    Backend AI password

Global Flags:
      --config string        Default config file (/Users/david.prangnell/Library/Application Support/k8sgpt/k8sgpt.yaml)
      --kubeconfig string    Path to a kubeconfig. Only required if out-of-cluster.
      --kubecontext string   Kubernetes context to use. Only required if out-of-cluster.
➜  k8sgpt auth add -b openai
Error: Model cannot be empty.
➜  k8sgpt auth add -b openai -m gpt-3.5-turbo
Enter openai Key: openai added to the AI backend provider list
```
