### ISSUE TITLE
[Feature]: Integration --no-install option

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#534]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

With the trivy integration, we assume we will install a trivy operator release.
There should be a `--no-install` mode to just activate the analyser without installing the release

### Benefits

Fits into an existing infrastructure stack

**Comment by panpan0000** [comment]
Can I?
