### ISSUE TITLE
[Question]: k8sgpt auth add for Azure OpenAI provider

### ISSUE THREAD

**Issue by hungry1526** [k8sgpt-ai/k8sgpt#557]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

k8sgpt: 0.3.11 (ee83aa1)

### Kubernetes Version

v1.25.6

### Host OS and its Version

MacOS

### Steps to reproduce

k8sgpt auth add --backend azureopenai --baseurl https://*****.openai.azure.com/ --engine ***** --model gpt-35-turbo
Enter azureopenai Key: 
azureopenai added to the AI backend provider list

k8sgpt analyze --explain --kubeconfig /Users/*****/.kube/config --backend azureopenai
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2a62e0a]**

goroutine 69 [running]:
github.com/k8sgpt-ai/k8sgpt/pkg/analyzer.MutatingWebhookAnalyzer.Analyze({}, {0xc000540c90, {0x3683ae0, 0xc000056090}, {0x0, 0x0}, {0x3684138, 0x49ae9c0}, 0x0, {0x0, ...}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analyzer/mutating_webhook.go:58 +0x60a
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis.func1({0x3668420, 0x49eded0}, 0x0?, 0x0?)
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:171 +0xd8
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:169 +0xa1d

Result is the same without passing down kubeconfig: k8sgpt analyze --explain --backend azureopenai

Does anyone know what does this error mean? Thank you! 

### Expected behaviour

Expect that command to run successfully. 

### Actual behaviour

Error out with a generic Go error.

**Comment by hungry1526** [comment]
I tried openai provider again and saw the similar error, anyone has clue? 

Setting up by following the instruction: 

k8sgpt analyze --explain
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2a6afce]

goroutine 30 [running]:
github.com/k8sgpt-ai/k8sgpt/pkg/analyzer.ValidatingWebhookAnalyzer.Analyze({}, {0xc000bacc30, {0x3683ae0, 0xc000126020}, {0x0, 0x0}, {0x36841e0, 0x49ae980}, 0x0, {0x0, ...}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/analyzer/validating_webhook.go:57 +0x5ee
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis.func1({0x36685a0, 0x49eded0}, 0x0?, 0xb0?)
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:171 +0xd8
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:169 +0xa1d

**Comment by AlexsJones** [comment]
Hi folks, thanks for putting this all in the same issue - it really helps.

If you disable the analyzer with `k8sgpt filters remove ValidatingWebhookAnalyzer` and re-run the analysis is it okay?

My suspicion is that your webhooks are missing a service name 
```
service, err := a.Client.GetClient().CoreV1().Services(svc.Namespace).Get(context.Background(), svc.Name, v1.GetOptions{})
```

This is where the code is failing and I "suspect" the svc.Name from the webhook is empty. 
I will look to build a guard on this just incase
