### ISSUE TITLE
Update Readme with new Analyzers

### ISSUE THREAD

**Issue by rakshitgondwal** [k8sgpt-ai/k8sgpt#575]
In https://github.com/k8sgpt-ai/k8sgpt/pull/553, two new analyzers were added:
- MutatingWebhookAnalyzer
- ValidatingWebhookAnalyzer

Update the Analyzers section in the Readme mentioning these two analyzers.

**Comment by AlexsJones** [comment]
@rakshitgondwal you need to make this a cross-folk PR so we can merge it please

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal you need to make this a cross-folk PR so we can merge it please

Done
