### ISSUE TITLE
`k8sgpt analyze --explain` failed when using local-ai with no auth

### ISSUE THREAD

**Issue by admun** [k8sgpt-ai/k8sgpt#577]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.13

### Kubernetes Version

1.26 (rke2)

### Host OS and its Version

fedora 38, Intel

### Steps to reproduce

1. setup local-ai w/ ggml-gpt4all-j model w/ helm, chart 2.1.0
2. install k8sgpt-operator from helm, chart 0.0.19
3. install k8sgpt w/ rpm
4. set localai as default provider, disable openai
5. run `k8sgpt analyze --explain`

### Expected behaviour

output more details to explain issues.

From reading, it should be showing more details how to triage/fix the issue (?)

### Actual behaviour

k8sgpt analyze --explain 
Service storage-provider/cluster.local-nfs-storage-provider-nfs-subdir-external-provisioner does not exist
   0% |                                                                                                                                                                                     | (0/27, 0 it/hr) [0s:0s]
Error: failed while calling AI provider localai: error, status code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.

 k8sgpt auth list
Default: 
> localai
Active: 
> localai
Unused: 
> openai
> azureopenai
> noopai
> cohere

### Additional Information

note that local-ai is setup w/ no auth (yes... I probably should have that, but I am just tire-kicking/smoke test on a homelab cluster)

**Comment by AlexsJones** [comment]
Thank you, this is a bug where the localai provider is not being picked up as default, as a work around you can set it manually after the explain with `-b localai`

**Comment by hobbytp** [comment]
I just tried the ```-b localai``` and did not meet the issue.

**Comment by admun** [comment]
Just to report back, I think I am still seeing the error w/ the work around...

```
 k8sgpt -b localai analyze --explain
Service storage-provider/cluster.local-nfs-storage-provider-nfs-subdir-external-provisioner does not exist
   0% |                                                                                                                                                                                       | (0/6, 0 it/hr) [0s:0s]
Error: failed while calling AI provider localai: error, status code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
```

**Comment by AlexsJones** [comment]
Apologies, will take a look as I can in the next days

**Comment by kamleshjec** [comment]
Hello Guys,

I am trying openai backend and following the steps mentioned in docs to add the auth key and getting below error on **--explain** 
 $k8sgpt analyze --explain
   0% |                                                                                                                                                                              | (0/1, 0 it/hr) [0s:0s]
Error: failed while calling AI provider openai: Post "https://api.openai.com/v1/chat/completions": tls: failed to verify certificate: x509: certificate signed by unknown authority

Is this someone can help to fix.. any help on this would be appreciated. Thanks a lot!

Another query : I am trying to generate another AI backend but everytime is pointing to openai backend only , do I need to do any other change anywhere before selecting another AI backend:

$k8sgpt generate cohere


Opening: https://beta.openai.com/account/api-keys to generate a key for openai

Please copy the generated key and run `k8sgpt auth` to add it to your config file

Thanks in advance.

**Comment by THE-BRAHMA** [comment]
I am still seeing this issue, I am using a localai as backend

<img width="1795" alt="Image" src="https://github.com/user-attachments/assets/9e8ee9b9-5baf-442b-af5a-a2d7bc056987" />

**Comment by kamleshjec** [comment]
> I am still seeing this issue, I am using a localai as backend
> 
> <img alt="Image" width="1795" src="https://private-user-images.githubusercontent.com/70097731/440261019-9e8ee9b9-5baf-442b-af5a-a2d7bc056987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY0MjM2MjIsIm5iZiI6MTc0NjQyMzMyMiwicGF0aCI6Ii83MDA5NzczMS80NDAyNjEwMTktOWU4ZWU5YjktNWJhZi00NDJiLWFmNWEtYTJkN2JjMDU2OTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTA1VDA1MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMGJkNTNiMDYwZDQyZDMwZGM2MjhlYWE0NmQxMzM1OTMwZTZlYjZmMGFmYWMzZGRiYmMyYjU0NTI2OTBiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.14NRxM2H7Q13jLlZtUGfUNvfF3jbgx98kB6373xy4IQ">

Hello , token seems invalid, please generate fresh token and try.

**Comment by THE-BRAHMA** [comment]
But if issue I generate token, it is chooses the Openai as provider, while I am using localAI

<img width="771" alt="Image" src="https://github.com/user-attachments/assets/073ce79e-e3a8-4341-b0c4-2e349504cba9" />
