### ISSUE TITLE
Multiclustering

### ISSUE THREAD

**Issue by HasseneFliss** [k8sgpt-ai/k8sgpt#578]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

K8sgpt is a very powerful tool but it has to be on the cluster that would analyze
I would say that based on my experience in the industry , it would have a lot of tools developed around k8sgpt , hence , the feature of multiclustering should be added.

In my actual company , we would need to have k8sgpt installed in a tooling cluster , to analyze issue in different clusters ( dev , qual and PRD ) .

Is there any plan to have this feature ?

### Solution Description

Having k8sgtp able to run in multi cluster mode.

For example:

Tooling Cluster : K8sgpt installed  --------->  Dev Cluster : Pod issue in Dev cluster can be analyzed using K8sgpt installed on Tooling cluster

### Benefits

So many tools will be developed around k8sgpt and it will be more beneficial to the industry.

**Comment by AlexsJones** [comment]
Thanks for the feedback, did you see the help?
```
 --kubeconfig string    Path to a kubeconfig. Only required if out-of-cluster.
      --kubecontext string   Kubernetes context to use. Only required if out-of-cluster.
```

You can provide cluster context to switch clusters dynamically. Would this suite your usecase?

**Comment by AlexsJones** [comment]
We will mark this as an idea for the future and close this out just now
