### ISSUE TITLE
Not getting any value in Details  while using any analyzer type( pod analyzer, ingress analyzer...etc ) . i am using azureopenai.. i am getting only text value

### ISSUE THREAD

**Issue by harshsing2891** [k8sgpt-ai/k8sgpt#595]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Host OS and its Version

linux

### Steps to reproduce

func ([PodAnalyzer](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/analyzer#PodAnalyzer)) Analyze(a [common](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/common).[Analyzer](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/common#Analyzer)) ([][common](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/common).[Result](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/common#Result), [error](https://pkg.go.dev/builtin#error))

### Expected behaviour

it should produce  details  as per below struct type

type Result struct {
	Kind         [string](https://pkg.go.dev/builtin#string)    `json:"kind"`
	Name         [string](https://pkg.go.dev/builtin#string)    `json:"name"`
	Error        [][Failure](https://pkg.go.dev/github.com/k8sgpt-ai/k8sgpt@v0.3.13/pkg/common#Failure) `json:"error"`
	Details      [string](https://pkg.go.dev/builtin#string)    `json:"details"`
	ParentObject [string](https://pkg.go.dev/builtin#string)    `json:"parentObject"`
}

**Comment by AlexsJones** [comment]
Can you provide some more details here? Such as the console output?

**Comment by AlexsJones** [comment]
Is this an
