### ISSUE TITLE
LocalAI: Deployment of helm chart with localai

### ISSUE THREAD

**Issue by gowthamc206** [k8sgpt-ai/k8sgpt#637]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

Hi Team,
I have tried with the given resources but unable to achieve the goal using helm chart for k8sgpt. 
Can I have steps to add secret and YAML file for "deploying k8sgpt resource".
Is there any thing that I need to change in the helm chart for k8sgpt?

please guide me...

with regards
Gowtham

### Solution Description

  unable to add secret and k8sgpt resources

### Benefits

will made work easy

**Comment by AlexsJones** [comment]
What is the error you are seeing? What is the reproducer for this?

**Comment by gowthamc206** [comment]
Hi, the logs for k8sgpt-deployment telling that "Connection refused", "request failed. failed while calling AI provider localai"
the logs of k8sgpt-operation-control-manager is "Finished Reconciling k8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = failed while calling AI provider localai: Post "http://10.106.39.14:8080/v1/chat/completions": dial tcp 10.106.39.14:8080: connect: connection refused"

What might be the error... Without helm deployment, in normal way it is working good.

**Comment by AlexsJones** [comment]
> Hi, the logs for k8sgpt-deployment telling that "Connection refused", "request failed. failed while calling AI provider localai" the logs of k8sgpt-operation-control-manager is "Finished Reconciling k8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = failed while calling AI provider localai: Post "http://10.106.39.14:8080/v1/chat/completions": dial tcp 10.106.39.14:8080: connect: connection refused"
> 
> What might be the error... Without helm deployment, in normal way it is working good.

Thanks for that, but can you advise what guide you are following? 
That kind of connection refused could be a networking issue but its very hard to guess.
Can you give us some more information about your K8s version, CNI and other details you might think are useful?

**Comment by AlexsJones** [comment]
Which version of LocalAI also?

**Comment by gowthamc206** [comment]
I have tried different ways
Try-1: https://itnext.io/k8sgpt-localai-unlock-kubernetes-superpowers-for-free-584790de9b65
Try-2: https://github.com/go-skynet/LocalAI/tree/master/examples/k8sgpt

I have modified only the k8sgpt resource file baseurl and the version. Other than every thing is same as in the documentation.

Versions:
Kubernetes: 1.23.4
Helm: V3.5.2
CNI:  calico/cni:v3.21.0

**Comment by AlexsJones** [comment]
Is this a multi node or single node cluster?

**Comment by gowthamc206** [comment]
for now it is single node cluster...

**Comment by arbreezy** [comment]
I suggest using the k8sgpt operator to manage the lifecycle of K8sgpt, is more battle-tested and has better documentation
