### ISSUE TITLE
[Question]: Unable to build on Arch on IPv4-only connection

### ISSUE THREAD

**Issue by xeruf** [k8sgpt-ai/k8sgpt#650]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

-

### Kubernetes Version

-

### Host OS and its Version

Manjaro Sway

### Steps to reproduce

1. Checkout repo
2. Run `make build`

### Expected behaviour

Build succeeds

### Actual behaviour

Tries to download golang packages from google servers via IPv6, even though the server ``proxy.golang.org` also has an IPv4 available, and fails because I am sadly on an IPv4-only connection right now, with many messages like this:
```
pkg/analysis/analysis.go:26:2: github.com/google/gnostic@v0.6.9: Get "https://proxy.golang.org/github.com/google/gnostic/@v/v0.6.9.zip": dial tcp: lookup proxy.golang.org on [2a02:2457:20c:101::126]:53: dial udp [2a02:2457:20c:101::126]:53: connect: network is unreachable
```

### Additional Information

Using AUR pacakge https://aur.archlinux.org/packages/k8sgpt-git

**Comment by AlexsJones** [comment]
Please try
```
export GOPROXY=direct
make build
```
