### ISSUE TITLE
[Bug]: K8sgpt serve is ending up in error

### ISSUE THREAD

**Issue by sandeepV2** [k8sgpt-ai/k8sgpt#651]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

0.3.13 (5ee8499)

### Kubernetes Version

v1.25.9

### Host OS and its Version

MacOS - Monterey 12.4 (intel)

### Steps to reproduce

$ k8sgpt serve
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b42b3b]

goroutine 1 [running]:
github.com/k8sgpt-ai/k8sgpt/cmd/serve.glob..func1(0x4b65980?, {0x3116263?, 0x0?, 0x0?})
	/home/runner/work/k8sgpt/k8sgpt/cmd/serve/serve.go:90 +0x53b
github.com/spf13/cobra.(*Command).execute(0x4b65980, {0x4bcb0d0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x4b61a40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/k8sgpt-ai/k8sgpt/cmd.Execute({0x3823d78?, 0x0?}, {0x38241f0?, 0x0?}, {0x311db16?, 0xc0000061a0?})
	/home/runner/work/k8sgpt/k8sgpt/cmd/root.go:59 +0xaa
main.main()
	/home/runner/work/k8sgpt/k8sgpt/main.go:25 +0x45
```

### Expected behaviour

We could have help with options that serve accepts.

like port and backend are mandatory options 

### Actual behaviour

It ends up in `SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b42b3b`

**Comment by AlexsJones** [comment]
Thanks for reporting this, I am scratching my head a bit here.
Can you try running this on alternative ports?
```
      --metrics-port string   Port to run the metrics-server on (default "8081")
  -p, --port string           Port to run the server on (default "8080")

```

**Comment by sandeepV2** [comment]
@AlexsJones yes we have to give message to the user as what option has to be used as you rightly pointed or run on default ports.

Right now as per documentation it asks the user to run `k8sgpt serve` which is ending up in segmentation violation. 

```
`➜  git:(main) ✗ k8sgpt serve  --backend localai
{"level":"info","ts":1695391786.6143749,"caller":"server/server.go:83","msg":"binding metrics to 8081"}
{"level":"info","ts":1695391786.615189,"caller":"server/server.go:68","msg":"binding api to 8080"}

^C
➜   git:(main) ✗ k8sgpt serve
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b42b3b]

goroutine 1 [running]:
github.com/k8sgpt-ai/k8sgpt/cmd/serve.glob..func1(0x4b65980?, {0x3116263?, 0x0?, 0x0?})
	/home/runner/work/k8sgpt/k8sgpt/cmd/serve/serve.go:90 +0x53b
github.com/spf13/cobra.(*Command).execute(0x4b65980, {0x4bcb0d0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x4b61a40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/k8sgpt-ai/k8sgpt/cmd.Execute({0x3823d78?, 0x0?}, {0x38241f0?, 0x2c799e0?}, {0x311db16?, 0xc0000061a0?})
	/home/runner/work/k8sgpt/k8sgpt/cmd/root.go:59 +0xaa
main.main()
	/home/runner/work/k8sgpt/k8sgpt/main.go:25 +0x45`
```

Hope it is clear now..

**Comment by Dkaykay** [comment]
Im getting the same error when running k8sgpt as operator in kubernetes. 

I played around a little to see performance of the analysis and deployed around 100 broken resources to the cluster. After a couple of minutes after deploying the broken resources, the pod shows this error and restarts:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1f7925b]

goroutine 1 [running]:
github.com/k8sgpt-ai/k8sgpt/cmd/serve.glob..func1(0x3fdbb00?, {0x2560590?, 0x0?, 0x0?})
	/workspace/cmd/serve/serve.go:90 +0x53b
github.com/spf13/cobra.(*Command).execute(0x3fdbb00, {0x40419a8, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x3fd7bc0)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/k8sgpt-ai/k8sgpt/cmd.Execute({0x2c7c524?, 0x0?}, {0x2c7c9b8?, 0x0?}, {0x2c811a0?, 0xc0000061a0?})
	/workspace/cmd/root.go:59 +0xaa
main.main()
	/workspace/main.go:25 +0x45`

The Results CRs are not getting created.

**Comment by AlexsJones** [comment]
> @AlexsJones yes we have to give message to the user as what option has to be used as you rightly pointed or run on default ports.
> 
> Right now as per documentation it asks the user to run `k8sgpt serve` which is ending up in segmentation violation.
> 
> ```
> `➜  git:(main) ✗ k8sgpt serve  --backend localai
> {"level":"info","ts":1695391786.6143749,"caller":"server/server.go:83","msg":"binding metrics to 8081"}
> {"level":"info","ts":1695391786.615189,"caller":"server/server.go:68","msg":"binding api to 8080"}
> 
> ^C
> ➜   git:(main) ✗ k8sgpt serve
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b42b3b]
> 
> goroutine 1 [running]:
> github.com/k8sgpt-ai/k8sgpt/cmd/serve.glob..func1(0x4b65980?, {0x3116263?, 0x0?, 0x0?})
> 	/home/runner/work/k8sgpt/k8sgpt/cmd/serve/serve.go:90 +0x53b
> github.com/spf13/cobra.(*Command).execute(0x4b65980, {0x4bcb0d0, 0x0, 0x0})
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
> github.com/spf13/cobra.(*Command).ExecuteC(0x4b61a40)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
> github.com/k8sgpt-ai/k8sgpt/cmd.Execute({0x3823d78?, 0x0?}, {0x38241f0?, 0x2c799e0?}, {0x311db16?, 0xc0000061a0?})
> 	/home/runner/work/k8sgpt/k8sgpt/cmd/root.go:59 +0xaa
> main.main()
> 	/home/runner/work/k8sgpt/k8sgpt/main.go:25 +0x45`
> ```
> 
> Hope it is clear now..

Apologies for the radio silence here, can you please try the latest k8sgpt version?
It's really not clear why we're seeing a panic here!

**Comment by arbreezy** [comment]
I couldn't reproduce a similar scenario w/o localai , eager to get more context if possible @Dkaykay
