### ISSUE TITLE
[Feature]: Improve k8sgpt auth error message

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#667]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

```
❯ go run main.go auth add openai
Error: Backend AI cannot be empty and accepted values are 'openai, localai, azureopenai, noopai, cohere'
```

This is very unhelpful and doesn't explain you need to use the backend flag

### Solution Description

```
❯ go run main.go auth add openai
Error: Backend AI cannot be empty and accepted values are 'openai, localai, azureopenai, noopai, cohere'
Example: "--backend openai"
To find out more use the `k8sgpt auth --help` flag
```

### Benefits

This makes it clearer and indicates to use the help

**Comment by adarshjhaa100** [comment]
@AlexsJones could work on this issue if its up for grabs

**Comment by arbreezy** [comment]
apologies@adarshjhaa100, I just assigned it to you

**Comment by adarshjhaa100** [comment]
Sure no problem @arbreezy. I understand everybody's busy in stuff

**Comment by adarshjhaa100** [comment]
@arbreezy has there been any fix for this issue already?  when I try to run:

`go run main.go auth add openai`

I get the following result. It seems that a default backend value is already configured.
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/31096082/4d474762-a77f-4922-987d-e7d6f1599a73)

**Comment by arbreezy** [comment]
Indeed there was a PR merged making output more descriptive.
Closing the issue now, feel free to pick up another one and chat in slack if you need help :)
