### ISSUE TITLE
[Bug]: trivy integration not active with —-no-install

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/k8sgpt#670]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

V0.3.15

### Kubernetes Version

V1.25.0

### Steps to reproduce

1. run k8sgpt integration activate trivy —no-install 
2. run k8sgpt integration list

Trivy will still be deactivated.

I think it is due to the fact that the isActivated method checks if the trivy helm chart is installed: https://github.com/k8sgpt-ai/k8sgpt/blob/4bfc7f996c851adadc5ab0754da6852979084e9d/pkg/integration/trivy/trivy.go#L111

When trivy is installed via ArgoCD this will always be false …

### Expected behaviour

K8sGPT should use a different check to find out if trivy integration is activated

### Actual behaviour

K8sGPT shows the wrong state of trivy integration

**Comment by AlexsJones** [comment]
This certainly is something that needs an improvement - rather than looking for the helm deployment we should check some other marker
