### ISSUE TITLE
[Feature]: AmazonBedrock AI provider 

### ISSUE THREAD

**Issue by stevensu1977** [k8sgpt-ai/k8sgpt#716]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

I use AWS EKS  and want use Amazon Bedrock Claude model, so I fork repo and write it. 

### Solution Description

Amazon Bedrock AI provider 

### Benefits

If you use AWS EKS, you can use k8sgpt from the Amazon Bedrock AI provider, and your data will only be kept in the Amazon VPC

**Comment by krrishdholakia** [comment]
Hey @stevensu1977 

Use [LiteLLM](https://github.com/BerriAI/litellm) for this. 

```shell
litellm --model bedrock/anthropic.claude-instant-v1

# OPENAI Compatible Server running on http://0.0.0.0:8000
```
```shell
k8sgpt auth add --backend localai --model bedrock/anthropic.claude-instant-v1 --baseurl http://0.0.0.0:8000 
```

**Comment by stevensu1977** [comment]
Hi @krrishdholakia 
Thanks your comments , LiteLLM is  good idea , it's a great project ,   but I just think if k8sgpt native support amazon bedrock that's be independently ,  like other k8s tools .
