### ISSUE TITLE
[Feature]: add cronjob max time flag

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt#770]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

add cronjob timeout flag `--cronjob-max-time`.
if not set k8sgpt does not detect cronjob timeout. and if set, detect cronjob timeout in analyzer.

### Benefits

cronjob is usually expected to end within a certain amount of time. 
many users will use this feature.

### Potential Drawbacks

not sure k8sgpt_operator can request with this flag

**Comment by AlexsJones** [comment]
I saw you deleted the repo @JuHyung-Son
