### ISSUE TITLE
[Feature]: Replace rest kubernetes client with controller-runtime clientset for Trivy integration analyzers

### ISSUE THREAD

**Issue by arbreezy** [k8sgpt-ai/k8sgpt#771]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Solution Description

We want to switch the k8s rest client to controller-runtime clientset which is already introduced. Effectively we are making requests to K8s api to fetch trivy CRs in a cluster and we just want to change the client interface

### Benefits

Thew new client is a prominent k8s client wrapper used by popular controllers and scaffolding projects like kube builder with great support of interacting with Custom resources.

Testing CRs is also more readable and easier with controller-runtime clientset methods than using a dynamic k8s client

**Comment by ptyin** [comment]
Hi, I'd like to have a try. Could you assign me this issue? I would get you informed my progress by this weekend.

**Comment by arbreezy** [comment]
Great assigning it to you @ptyin , you can check the gateway analysers to see an example, the goal is to deprecate the rest client.
