### ISSUE TITLE
[Feature]: Add system role in message

### ISSUE THREAD

**Issue by jmyung** [k8sgpt-ai/k8sgpt#774]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

System role doesn't exist in message now.

## Before
```
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    "user",
				Content: fmt.Sprintf(promptTmpl, c.language, prompt),
			},
		},
```

## After
```
		Messages: []openai.ChatCompletionMessage{
			{
				Role: "system",
				Content: "You are a helpful Kubernetes assistant",
			},
			{
				Role:    "user",
				Content: fmt.Sprintf(promptTmpl, c.language, prompt),
			},
		},
```

### Benefits

If system role for kubernetes assistant is added, I think it would be more explicit.

### Additional Information

If it is okay, I can add role at GetCompletion function in [pkg/ai/openai.go](https://github.com/k8sgpt-ai/k8sgpt/blob/71ae5a73014e057bf14eb4a7f59a22163a1063c7/pkg/ai/openai.go#L73).

**Comment by arbreezy** [comment]
I am curious @jmyung have you seen any difference on the responses when you define the role like that ?

**Comment by jmyung** [comment]
@arbreezy I think It doesn't make any difference yet. 😅 Let me close for now.
