### ISSUE TITLE
[Bug]: Incorrect error during output selection

### ISSUE THREAD

**Issue by pavneeta** [k8sgpt-ai/k8sgpt#815]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Host OS and its Version

Ubunto 2204

### Steps to reproduce

1. Run `k8sgpt analyze --explain -output=json`

2. The actual issue is  single hyphen before output, but the error says :

`Error: unsupported output format: utput=json. Available format json,text`

### Expected behaviour

The error message should be: 

`error: -output is not a supported command for K8sgpt, try --output=<>`

### Actual behaviour

The actual issue is  single hyphen before output, but the error says :

`Error: unsupported output format: utput=json. Available format json,text`

**Comment by AlexsJones** [comment]
Please use `--output` double dash
