### ISSUE TITLE
[Question]: Update Copyright Year in project

### ISSUE THREAD

**Issue by amitamrutiya2210** [k8sgpt-ai/k8sgpt#895]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.26

### Kubernetes Version

v1.29.1

### Host OS and its Version

Linux

### Steps to reproduce

Open the each and every file where copyright comment is present.
Look at the copyright notice at the top of the file.

### Expected behaviour

The copyright notice should read `Copyright 2024 The K8sGPT Authors`. As we are now in the year 2024, this should be updated to reflect the current year.

### Actual behaviour

The copyright notice currently reads `Copyright 2023 The K8sGPT Authors` in comments.

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/91112485/a2cb8f0c-a393-47fe-b54c-7724dbdd2cf3)

### Additional Information

This is a minor issue, but it's important to keep our copyright notices up to date. This helps to ensure that our project is legally protected and that the information we provide to our users and contributors is accurate. If @AlexsJones or @arbreezy  agrees, I would be happy to work on this issue. It would be a great opportunity for me to start exploring this repository.

**Comment by AlexsJones** [comment]
The copyright notice on a work establishes a claim to copyright. The date on the notice establishes how far back the claim is made. This means if you update the date, you are no longer claiming the copyright for the original date and that means if somebody has copied the work in the meantime and they claim its theirs on the ground that their publishing the copy was before your claim, then it will be difficult to establish who is the originator of the work.
