### ISSUE TITLE
[Bug]: Unused variable warning in mutating_webhook.go

### ISSUE THREAD

**Issue by amitamrutiya2210** [k8sgpt-ai/k8sgpt#901]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.26

### Kubernetes Version

v1.29.1

### Host OS and its Version

Linux

### Steps to reproduce

1. Go to 'mutating_webhook.go'
2. Scroll down to the code block where `failures` is appended for first time when service is not found case
3. Notice the warning "this value of `failures` is never used"

### Expected behaviour

The `failures` variable should be used after being declared and appended to, or it should be removed if it's not needed.

### Actual behaviour

In the file `mutating_webhook.go`, there's a warning indicating that the variable failures is declared but never used. This implies that in the current code structure, if an error occurs while creating services, we append the failure but continue the loop without storing it. As a result, this failure is never accounted for.

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/91112485/3df6eb71-2a7e-4070-b34d-d1c66d298497)

### Additional Information

This warning could potentially indicate dead code or a bug where the `failures` variable should be used but isn't. It's also a code quality issue as unused variables can lead to confusion and make the code harder to understand. If this issue is valid then I want to fix this.

**Comment by amitamrutiya2210** [comment]
Due to the continue statement, the code exits the inner for loop prematurely, causing line 133 to never execute. I also tested it in cases where no service is defined, and in such instances, it does not return any result.

https://github.com/k8sgpt-ai/k8sgpt/blob/60853fe4eb8de7a1fdbaea388c3d2d6205e273a6/pkg/analyzer/mutating_webhook.go#L78

**Comment by VaibhavMalik4187** [comment]
> Due to the continue statement, the code exits the inner for loop prematurely, causing line 133 to never execute. I also tested it in cases where no service is defined, and in such instances, it does not return any result.
> 
> https://github.com/k8sgpt-ai/k8sgpt/blob/60853fe4eb8de7a1fdbaea388c3d2d6205e273a6/pkg/analyzer/mutating_webhook.go#L78

Ahh, now I get it. Great analysis!

**Comment by VaibhavMalik4187** [comment]
> Also, there is same bug on `validating_webhook.go`
> 
> https://github.com/k8sgpt-ai/k8sgpt/blob/60853fe4eb8de7a1fdbaea388c3d2d6205e273a6/pkg/analyzer/validating_webhook.go#L59-L78

Yepp. I saw noticed this too in https://github.com/k8sgpt-ai/k8sgpt/actions/runs/7746749007/job/21166974081
