### ISSUE TITLE
Introduction and Offer to Contribute

### ISSUE THREAD

**Issue by xilu0** [k8sgpt-ai/k8sgpt#918]
Hello k8sgpt team,

My name is Yijie Wang, and I am reaching out to express my interest in contributing to the k8sgpt project. I am a software engineer with experience in Go development, and I am eager to apply my skills to contribute to your project. I have been following k8sgpt for some time now and am impressed by its goals and the community around it.

I am open to working on any functionality that needs development or improvement. My goal is to dedicate two days each week to contributing to the project. However, as I am new to this particular project, I would appreciate some time to adapt and get familiar with your codebase and contribution guidelines.

I am keen to learn from the community and to share my knowledge and skills to help the project grow. 

Looking forward to your guidance and hoping to make a positive impact on k8sgpt.

Best regards,
Yijie Wang

**Comment by AlexsJones** [comment]
Please feel free to connect with us on Slack. You're also very welcome to try and solve some of the incoming issues if you are already familiar with the code base.

**Comment by xilu0** [comment]
Hello, @AlexsJones 
I recently encountered an issue while attempting to register for the k8sgpt Slack workspace. It appears that registration requires an email address specific to the domain associated with k8sgpt, which I currently do not have access to. This limitation prevents me from joining the Slack workspace and participating in the community discussions.
Could you please advise if there is an alternative method for joining the Slack workspace or if it's possible to receive an invitation to register with a non-domain-specific email address? 
Thank you for your assistance and looking forward to your guidance on how I can become a part of the Slack community.

**Comment by AlexsJones** [comment]
Try this @xilu0  https://join.slack.com/t/k8sgpt/shared_invite/zt-276pa9uyq-pxAUr4TCVHubFxEvLZuT1Q

**Comment by xilu0** [comment]
> Try this @xilu0 https://join.slack.com/t/k8sgpt/shared_invite/zt-276pa9uyq-pxAUr4TCVHubFxEvLZuT1Q

I wanted to extend my heartfelt thanks for providing me with the invitation link to the k8sgpt Slack workspace. I have successfully joined the Slack community。
I am eager to start contributing and learning more about the project.
