### ISSUE TITLE
[Bug]: auth list doesn't show password even if user input is set

### ISSUE THREAD

**Issue by VaibhavMalik4187** [k8sgpt-ai/k8sgpt#936]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Host OS and its Version

Ubuntu 23.10

### Steps to reproduce

1. `./bin/k8sgpt auth list --details`
2. On the show password prompt, write `y`

### Expected behaviour

K8sGPT should show the backend configurations along with the passwords.

### Actual behaviour

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/34866732/5aafa750-ab47-49d9-a86e-95fb6eee8705)

Passwords are not displayed even after setting the user input as `y`

### Additional Information

I'm working on the CLI backend configuration overhaul and would like to include a fix for this issue in that PR itself if that's acceptable.

**Comment by AlexsJones** [comment]
I am not sure we should be exposing the passwords via the UI. Do you have a use case as an example?

**Comment by VaibhavMalik4187** [comment]
Use case: Say, I want to confirm if the backend config I'm using is using the right API keys but I don't want to navigate to the config file and confirm it there.

If this use case is not helpful, then it'd be better to get rid of the `details` flag because it's not being used.
