### ISSUE TITLE
[Bug]: Panic on running the serve command

### ISSUE THREAD

**Issue by VaibhavMalik4187** [k8sgpt-ai/k8sgpt#968]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Host OS and its Version

Ubuntu 23.10

### Steps to reproduce

1. Run `./bin/k8sgpt serve`

### Expected behaviour

k8sgpt should run as a server.

### Actual behaviour

k8sgpt panicked:
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/34866732/5eb1bbd5-e93e-4ad2-9183-6c2c9002d95a)

**Comment by VaibhavMalik4187** [comment]
@JuHyung-Son, I've opened this issue to track https://github.com/k8sgpt-ai/k8sgpt/pull/966#issuecomment-1951575817. Looks like this problem was introduces by f2138c71017b391625eebdfb4c5708c824824f69. I've not found the root cause of the problem just yet but a quick fix is to change:
`ServeCmd.Flags().BoolVarP(&enableHttp, "http", "h", false, "Enable REST/http using gppc-gateway")` to `ServeCmd.Flags().BoolVarP(&enableHttp, "http", "", false, "Enable REST/http using gppc-gateway")`

**Comment by VaibhavMalik4187** [comment]
Looks like the shorthand `h` defined for the `http` flag is having problems because the `help` flag also uses `h` as the shorthand.

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/34866732/92f04f4a-c2e5-4a0e-9afa-49e33af8c47b)

**Comment by JuHyung-Son** [comment]
yes there should be proper replacement character

**Comment by JuHyung-Son** [comment]
hmm giving capital letter looks awkward. like first suggest, let`s just not set shorthand.

**Comment by VaibhavMalik4187** [comment]
> hmm giving capital letter looks awkward. like first suggest, let`s just not set shorthand.

Makes sense. I've opened a PR to address this issue.
