### ISSUE TITLE
add label selector on analyzer cmd

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt#993]
add label selector like `kubectl get pod -l app=test`

cmd document will be same as kubectl description

```
-L, --label-columns=[]:
	Accepts a comma separated list of labels that are going to be presented as columns. Names are case-sensitive.
	You can also use multiple flag options like -L label1 -L label2...
```

**Comment by SambariManikanta09** [comment]
Can I get more insight on this issue, steps to solve it..
Love to contribute to the project

**Comment by JuHyung-Son** [comment]
@SambariManikanta09 would you do this?
